# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
services:
  mo_ldap_import_export:
    environment:
      LDAP_CONTROLLERS: '[{"host": "ad.addev.magentahosted.dk"}]'
      LDAP_DOMAIN: "magenta.dk"
      LDAP_SEARCH_BASE: "DC=ad,DC=addev"
      LDAP_OUS_TO_SEARCH_IN: '["OU=Users,OU=ldap-tests,OU=OS2MO"]'
      LDAP_OUS_TO_WRITE_TO: '["OU=Users,OU=ldap-tests,OU=OS2MO"]'
      LDAP_OU_FOR_NEW_USERS: "OU=Users,OU=ldap-tests,OU=OS2MO"
      LDAP_DIALECT: "AD"
      LDAP_OBJECT_CLASS: "user"
      LDAP_CPR_ATTRIBUTE: "employeeID"
      LDAP_IT_SYSTEM: "Active Directory"

      LDAP_AUTH_METHOD: "simple"

      LISTEN_TO_CHANGES_IN_MO: "True"
      LISTEN_TO_CHANGES_IN_LDAP: "True"

      PRODUCTION: "False"

      CONVERSION_MAPPING: >-
        {
          "ldap_to_mo": {
            "Employee": {
              "objectClass": "ramodels.mo.employee.Employee",
              "_import_to_mo_": "true",
              "_ldap_attributes_": ["employeeID", "initials"],
              "cpr_number": "{{ ldap.employeeID|strip_non_digits or '' }}",
              "uuid": "{{ employee_uuid or '' }}",
              "given_name": "{{ get_employee_dict(employee_uuid).given_name }}",
              "surname": "{{ get_employee_dict(employee_uuid).surname }}",
              "nickname_given_name": "{{ get_employee_dict(employee_uuid).nickname_given_name }}",
              "nickname_surname": "{{ get_employee_dict(employee_uuid).nickname_surname }}",
              "user_key": "{{ ldap.initials }}"
            },
            "Engagement": {
              "objectClass": "ramodels.mo.details.engagement.Engagement",
              "_import_to_mo_": "true",
              "_ldap_attributes_": ["title"],
              "person": "{{ employee_uuid or '' }}",
              "user_key": "{{ get_primary_engagement_dict(employee_uuid).user_key }}",
              "engagement_type": "{{ get_primary_engagement_dict(employee_uuid).engagement_type_uuid }}",
              "org_unit": "{{ get_primary_engagement_dict(employee_uuid).org_unit_uuid }}",
              "job_function": "{{ get_primary_engagement_dict(employee_uuid).job_function_uuid }}",
              "primary": "{{ get_primary_engagement_dict(employee_uuid).primary_uuid }}",
              "uuid": "{{ get_primary_engagement_dict(employee_uuid).uuid }}",
              "extension_2": "{{ ldap.title }}"
            },
            "Active Directory": {
              "objectClass": "ramodels.mo.details.it_system.ITUser",
              "_import_to_mo_": "true",
              "_ldap_attributes_": ["objectGUID", "sAMAccountName"],
              "uuid": "{{ ldap.objectGUID|remove_curly_brackets }}",
              "user_key": "{{ ldap.sAMAccountName }}",
              "itsystem": "{{ get_it_system_uuid('Active Directory') }}",
              "person": "{{ employee_uuid or '' }}"
            }
          },
          "mo_to_ldap": {
            "Employee": {
              "employeeID": "{{ mo_employee.cpr_number }}",
              "sn": "{{ mo_employee.nickname_surname or mo_employee.surname}}",
              "displayName": "{{mo_employee.nickname_given_name or mo_employee.given_name}} {{mo_employee.nickname_surname or mo_employee.surname}}"
            },
            "Engagement": {
              "title": "{{ mo_employee_engagement.user_key }}"
            },
            "Active Directory": {
              "objectGUID": "{{ mo_employee_it_user.uuid  }}",
              "sAMAccountName": "{{ mo_employee_it_user.user_key }}"
            }
          },
          "username_generator": {
            "objectClass": "UserNameGenerator",
            "combinations_to_try": ["FFFX", "LLLX"]
          }
        }

    env_file:
      secrets.txt
