version: "3"
services:
  ldap:
    container_name: ldap
    image: osixia/openldap:1.5.0
    command: ["--copy-service", "--loglevel", "debug"]
    environment:
      LDAP_ORGANISATION: "magenta"
      LDAP_DOMAIN: "magenta.dk"
      LDAP_ADMIN_PASSWORD: "AdminPassword123"
      LDAP_CONFIG_PASSWORD: "ConfigPassword123"

      LDAP_LOG_LEVEL: 512
    volumes:
      - ./dev-environment/ldif/:/container/service/slapd/assets/config/bootstrap/ldif/custom/:ro
      - ./dev-environment/schema/:/container/service/slapd/assets/config/bootstrap/schema/custom/:ro
    networks:
      - os2mo_default
#    ports:
#      - "389:389"

  mo_ldap_import_export:
    container_name: mo_ldap_ie
    build: .
    env_file:
      ./dev-environment/mo_ldap_import_export.env
    volumes:
      - ./mo_ldap_import_export:/opt/mo_ldap_import_export/
    networks:
      - os2mo_default
    ports:
      - "8000:8000"
    depends_on:
      ldap-db:
        condition: service_healthy


  ldap-db:
    image: postgres:11.7  # Set image in global.sls
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ldap-integration
    networks:
      - os2mo_default
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s


networks:
  os2mo_default:
    external: true
