# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
services:

  mo_ldap_import_export:
    container_name: mo_ldap_ie
    build: .
    command: ["uvicorn", "--factory", "app.main:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      FASTRAMQPI__DAP: "true"
      TZ: "Europe/Copenhagen"
    volumes:
      - ./mo_ldap_import_export:/opt/app/
      - ./dev-environment/magenta_addev_mapping.txt:/var/run/.env
    networks:
      - os2mo_default
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:5678:5678"
    env_file:
      - secrets.txt
      - ./dev-environment/magenta-addev.env

networks:
  os2mo_default:
    external: true
