# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
version: "3"
services:
  ldap:
    container_name: ldap
    image: osixia/openldap:1.5.0
    command: ["--copy-service", "--loglevel", "debug"]
    environment:
      LDAP_ORGANISATION: "magenta"
      LDAP_DOMAIN: "magenta.dk"
      LDAP_ADMIN_PASSWORD: "AdminPassword123"
      LDAP_CONFIG_PASSWORD: "ConfigPassword123"

      LDAP_LOG_LEVEL: 512
    volumes:
      - ./dev-environment/ldif/:/container/service/slapd/assets/config/bootstrap/ldif/custom/:ro
      - ./dev-environment/schema/:/container/service/slapd/assets/config/bootstrap/schema/custom/:ro
    networks:
      - os2mo_default
#    ports:
#      - "389:389"

  amqp2http:
    image: magentaaps/amqp2http:1.0.0
    command: ["uvicorn", "--factory", "app.main:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker"
      FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
      FASTRAMQPI__MO_URL: "http://mo:5000"

      FASTRAMQPI__CLIENT_ID: "dipex"
      FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"

      FASTRAMQPI__AMQP__UPSTREAM_EXCHANGE: os2mo
      FASTRAMQPI__AMQP__EXCHANGE: os2mo_ldap
      FASTRAMQPI__AMQP__QUEUE_PREFIX: os2mo_ldap

      NAME: "mo2ldap"
      INTEGRATION_URL: "http://mo_ldap_ie:8000"
      EVENT_MAPPING: '{"person": "/mo2ldap/person"}'
    networks:
      - os2mo_default

  mo_ldap_import_export:
    container_name: mo_ldap_ie
    build: .
    command: ["uvicorn", "--factory", "app.main:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      FASTRAMQPI__DAP: "true"
      TZ: "Europe/Copenhagen"
    volumes:
      - ./mo_ldap_import_export:/opt/app/
      - ./dev-environment/mo_ldap_import_export.env:/var/run/.env
    networks:
      - os2mo_default
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:5678:5678"

networks:
  os2mo_default:
    external: true
