# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections.abc import Awaitable
from collections.abc import Callable
from typing import cast
from uuid import UUID

import pytest
from fastramqpi.context import Context
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client import ITUserCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.autogenerated_graphql_client.client import GraphQLClient
from mo_ldap_import_export.dataloaders import DataLoader
from mo_ldap_import_export.environments.main import find_mo_employee_uuid
from mo_ldap_import_export.utils import combine_dn_strings
from tests.integration.conftest import AddLdapPerson


@pytest.fixture
def dataloader(test_client: AsyncClient, context: Context) -> DataLoader:
    return cast(DataLoader, context["user_context"]["dataloader"])


@pytest.mark.integration_test
async def test_find_mo_employee_uuid_cpr_match(
    dataloader: DataLoader,
    ldap_person_dn: str,
    mo_person: UUID,
) -> None:
    # mo_person and ldap_person share the same CPR (2108613133)
    result = await find_mo_employee_uuid(dataloader, ldap_person_dn)
    assert result == mo_person


@pytest.mark.integration_test
async def test_find_mo_employee_uuid_not_found(
    dataloader: DataLoader,
    add_ldap_person: AddLdapPerson,
) -> None:
    # Create LDAP person with a valid but non-matching CPR
    dn_parts = await add_ldap_person("unknown_user", "0101700000")
    dn = combine_dn_strings(dn_parts)

    result = await find_mo_employee_uuid(dataloader, dn)
    assert result is None


@pytest.mark.integration_test
async def test_find_mo_employee_uuid_ituser_match(
    dataloader: DataLoader,
    add_ldap_person: AddLdapPerson,
    mo_person: UUID,
    graphql_client: GraphQLClient,
    read_itsystem_by_user_key: Callable[[str], Awaitable[UUID]],
) -> None:
    # Create LDAP person with non-matching CPR but we will match via ITUser
    dn_parts = await add_ldap_person("ituser_user", "0202700000")
    dn = combine_dn_strings(dn_parts)

    # Get the unique ID from LDAP
    ldap_uuid = await dataloader.ldapapi.get_ldap_unique_ldap_uuid(dn)

    # Find the ITSystem used for correlation
    itsystem_uuid = await read_itsystem_by_user_key("ADUUID")

    # Create an ITUser in MO for the person, using the LDAP UUID as user_key
    await graphql_client.ituser_create(
        input=ITUserCreateInput(
            user_key=str(ldap_uuid),
            person=mo_person,
            itsystem=itsystem_uuid,
            validity=RAValidityInput(from_="2000-01-01T00:00:00Z"),  # type: ignore
        )
    )

    # Now find_mo_employee_uuid should find the person via ITUser matching
    result = await find_mo_employee_uuid(dataloader, dn)
    assert result == mo_person
