# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections.abc import Awaitable
from collections.abc import Callable
from typing import cast
from uuid import UUID
from uuid import uuid4

import pytest
from fastramqpi.context import Context
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client import ITUserCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.autogenerated_graphql_client.client import GraphQLClient
from mo_ldap_import_export.dataloaders import DataLoader
from mo_ldap_import_export.types import CPRNumber
from mo_ldap_import_export.utils import combine_dn_strings
from tests.integration.conftest import AddLdapPerson


@pytest.fixture
def dataloader(test_client: AsyncClient, context: Context) -> DataLoader:
    return cast(DataLoader, context["user_context"]["dataloader"])


@pytest.mark.integration_test
@pytest.mark.parametrize(
    "cpr,match",
    [
        # Matches mo_person
        (CPRNumber("2108613133"), True),
        # Valid CPR, not mo_person
        (CPRNumber("0101700000"), False),
        # Neither GUID nor CPR provided
        (None, False),
    ],
)
async def test_cpr_match(
    dataloader: DataLoader,
    mo_person: UUID,
    cpr: CPRNumber | None,
    match: bool,
) -> None:
    result = await dataloader.find_mo_employee_uuid_by_guid_and_cpr(None, cpr)
    assert result == (mo_person if match else None)


@pytest.mark.integration_test
async def test_ituser_match(
    dataloader: DataLoader,
    add_ldap_person: AddLdapPerson,
    mo_person: UUID,
    graphql_client: GraphQLClient,
    read_itsystem_by_user_key: Callable[[str], Awaitable[UUID]],
) -> None:
    dn_parts = await add_ldap_person("mo_person_account_prev_cpr", "0202700000")
    dn = combine_dn_strings(dn_parts)
    ldap_uuid = await dataloader.ldapapi.get_ldap_unique_ldap_uuid(dn)

    # Bind the LDAP UUID to mo_person via an ITUser.
    itsystem_uuid = await read_itsystem_by_user_key("ADUUID")
    await graphql_client.ituser_create(
        input=ITUserCreateInput(
            user_key=str(ldap_uuid),
            person=mo_person,
            itsystem=itsystem_uuid,
            validity=RAValidityInput(from_="2000-01-01T00:00:00Z"),  # type: ignore
        )
    )

    result = await dataloader.find_mo_employee_uuid_by_guid_and_cpr(ldap_uuid)
    assert result == mo_person


@pytest.mark.integration_test
async def test_unknown_guid_no_match(dataloader: DataLoader) -> None:
    result = await dataloader.find_mo_employee_uuid_by_guid_and_cpr(uuid4())
    assert result is None
