# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from unittest.mock import MagicMock
from uuid import uuid4

import pytest
from pydantic import ValidationError
from pydantic import parse_obj_as

from mo_ldap_import_export.autogenerated_graphql_client.client import GraphQLClient
from mo_ldap_import_export.config import Settings
from mo_ldap_import_export.config import UsernameGeneratorConfig
from mo_ldap_import_export.dataloaders import DataLoader
from mo_ldap_import_export.environments.generate_username import _create_from_combi
from mo_ldap_import_export.environments.generate_username import generate_username
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.main import GRAPHQL_VERSION
from mo_ldap_import_export.moapi import MOAPI
from mo_ldap_import_export.usernames import UserNameGenerator
from tests.graphql_mocker import GraphQLMocker


@pytest.mark.parametrize(
    "name,combi,expected",
    [
        # Test with a combi using middle names
        (["Nick", "Alfa", "Beta", "Gamma", "Janssen"], "F123L", "nabgj"),
        # Test with a combi that starts with an 'X'
        (["Nick", "Janssen"], "XFL", "Xnj"),
        # Test with a combi that starts with multiple 'X's
        (["Nick", "Janssen"], "XXFL", "XXnj"),
        # Test with a combi that ends with an 'X'
        (["Nick", "Janssen"], "FFLLX", "nijaX"),
        # Test with a combi that ends with multiple 'X's
        (["Nick", "Janssen"], "FFXXX", "niXXX"),
        # Test with a combi that has 'X's spread
        (["Nick", "Janssen"], "XFXLX", "XnXjX"),
        # Test with a combis that mixes first and last name
        (["Nick", "Janssen"], "FLFLF", "njnjn"),
        (["Nick", "Janssen"], "FFLLF", "nijan"),
        # Test with a combi that expects exactly 4 characters for the first name
        (["Nick", "Janssen"], "FFFFL", "nickj"),
        # Test with a combi that expects 5 characters for the first name
        (["Nick", "Janssen"], "FFFFFL", None),
        # Test with a combi that expects exactly 4 characters for the surname
        (["Nick", "Jans"], "FLLLL", "njans"),
        # Test with a combi that expects 5 characters for the surname
        (["Nick", "Jans"], "FLLLLL", None),
        # Test with a user without a first name
        (["", "Janssen"], "FFLL", None),
        (["Janssen"], "FFLL", None),
        # Test with a user without a surname
        (["Nick", ""], "FFLL", None),
        (["Nick"], "FFLL", None),
        # Test with a with an empty middlename
        (["Nick", "", "Janssen"], "FF1LL", None),
        # Test combis expecting middle names on user without a middle names
        (["Nick", "Janssen"], "FF1LL", None),
        (["Nick", "Janssen"], "FF2LL", None),
        (["Nick", "Janssen"], "FF3LL", None),
    ],
)
def test_create_from_combi(
    name: list[str],
    combi: str,
    expected: str | None,
) -> None:
    username = _create_from_combi(name, combi)
    assert username == expected


def test_check_combinations_to_try():
    config = {"combinations_to_try": ["GAK"]}
    with pytest.raises(ValidationError, match="Incorrect combination"):
        parse_obj_as(UsernameGeneratorConfig, config)


@pytest.mark.usefixtures("minimal_valid_environmental_variables")
async def test_active_directory_search_result(
    graphql_mock: GraphQLMocker, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv(
        "CONVERSION_MAPPING",
        json.dumps({"username_generator": {"combinations_to_try": ["FFFX", "LLLX"]}}),
    )

    employee_uuid = uuid4()
    route = graphql_mock.query("read_employees")
    route.result = {
        "employees": {
            "objects": [
                {
                    "validities": [
                        {
                            "uuid": employee_uuid,
                            "user_key": "myuser",
                            "cpr_number": None,
                            "given_name": "Aage",
                            "surname": "Klarskov",
                            "nickname_given_name": "",
                            "nickname_surname": "",
                            "validity": {"from": "1970-01-01T00:00:00Z", "to": None},
                        }
                    ]
                }
            ]
        }
    }

    settings = Settings()

    graphql_client = GraphQLClient(f"http://example.com/graphql/v{GRAPHQL_VERSION}")
    moapi = MOAPI(settings, graphql_client)

    ldap_connection = MagicMock()
    ldap_connection.search.return_value = (
        None,
        {
            # Status 0 means success
            # See RFC4511 (Section 4.1.9 - Result Message) for details
            "result": 0,
            "description": "success",
            "dn": "",
            "message": "",
            "referrals": None,
            "type": "searchResDone",
        },
        [
            # Whenever a search is done in Active Directory, even if it returns no results,
            # these entries are returned as ldap3 does not support resolving these.
            #
            # This is an Active Directory specific issue, as OpenLDAP correctly returns the
            # empty result set instead, presumably because ldap3 actually can resolve the
            # references returned.
            {
                "uri": [
                    "ldap://ForestDnsZones.kommune.dk/DC=ForestDnsZones,DC=kommune,DC=dk",
                ],
                "type": "searchResRef",
            },
            {
                "uri": [
                    "ldap://DomainDnsZones.kommune.dk/DC=DomainDnsZones,DC=kommune,DC=dk",
                ],
                "type": "searchResRef",
            },
            {
                "uri": [
                    "ldap://kommune.dk/CN)Configuration,DC=kommune,DC=dk",
                ],
                "type": "searchResRef",
            },
        ],
        None,
    )

    ldapapi = LDAPAPI(settings, ldap_connection)
    username_generator = UserNameGenerator(settings, ldap_connection)

    dataloader = DataLoader(settings, moapi, ldapapi, username_generator)

    username = await generate_username(dataloader, employee_uuid)
    assert username == "aag2"
