# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Integration tests for the ITUser `binding_type` field."""

import json
from collections.abc import Awaitable
from collections.abc import Callable
from uuid import UUID

import pytest
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import ITUserFilter
from mo_ldap_import_export.autogenerated_graphql_client import (
    ReadItusersItusersObjectsValidities,
)
from mo_ldap_import_export.autogenerated_graphql_client import (
    ReadItusersItusersObjectsValiditiesValidity,
)
from mo_ldap_import_export.types import LDAPUUID
from mo_ldap_import_export.utils import mo_today


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo_any": {
                    "inetOrgPerson": [
                        {
                            "objectClass": "ITUser",
                            "_import_to_mo_": "true",
                            "_ldap_attributes_": ["entryUUID", "employeeNumber"],
                            "uuid": "{{ get_ituser_uuid({'external_ids': [ldap.entryUUID|string]}) }}",
                            "user_key": "{{ ldap.entryUUID }}",
                            "external_id": "{{ ldap.entryUUID }}",
                            "itsystem": "{{ get_it_system_uuid('ADUUID') }}",
                            "person": "{{ get_person_uuid({'cpr_numbers': [ldap.employeeNumber]}) }}",
                            "binding_type": "implicit",
                        },
                    ],
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("test_client")
async def test_ituser_binding_type_ldap_to_mo(
    graphql_client: GraphQLClient,
    ldap_person_uuid: LDAPUUID,
    mo_person: UUID,
    aduuid: UUID,
    trigger_ldap_person: Callable[[], Awaitable[None]],
) -> None:
    """`binding_type` from the conversion mapping must end up on the MO ITUser."""
    await trigger_ldap_person()

    ituser_uuid = one(
        (
            await graphql_client.read_ituser_uuid(
                filter=ITUserFilter(
                    external_ids=[str(ldap_person_uuid)],
                    binding_types=["implicit"],
                )
            )
        ).objects
    ).uuid
    itusers = (await graphql_client.read_itusers(uuids=[ituser_uuid])).objects
    ituser = one(itusers)

    validity = one(ituser.validities)
    assert validity == ReadItusersItusersObjectsValidities(
        user_key=str(ldap_person_uuid),
        validity=ReadItusersItusersObjectsValiditiesValidity(from_=mo_today(), to=None),
        employee_uuid=mo_person,
        itsystem_uuid=aduuid,
        engagement_uuids=[],
        rolebindings=[],
        external_id=str(ldap_person_uuid),
        binding_type="implicit",
    )
