# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import Awaitable
from collections.abc import Callable
from uuid import UUID

import pytest
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import ITUserFilter


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "ADtitle": {
                        "objectClass": "ITUser",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": [],
                        # NOTE: `user_key`is not a valid field on ITUserFilter.
                        # It should have been `user_keys` to work as expected.
                        "uuid": """
                            {{
                                get_ituser_uuid({
                                    'user_key': 'should have been user_keys',
                                    'itsystem': {'user_keys': ['ADtitle']},
                                    'employee': {'uuids': [employee_uuid]},
                                })
                            }}",
                        """,
                        "user_key": "from-ldap",
                        "person": "{{ employee_uuid }}",
                        "itsystem": "{{ get_it_system_uuid('ADtitle') }}",
                    },
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("adtitle")
async def test_get_ituser_uuid_ignores_unknown_kwargs(
    graphql_client: GraphQLClient,
    trigger_ldap_person: Callable[[], Awaitable[None]],
    mo_person: UUID,
) -> None:
    """Prove that misspelled filter kwargs are silently dropped."""
    # Prove that no ITUsers exist at the start of the test.
    before = await graphql_client._testing__ituser_read(
        filter=ITUserFilter(employee=EmployeeFilter(uuids=[mo_person])),
    )
    assert before.objects == []

    await trigger_ldap_person()

    # We would have expected a failure due to the misspelled filter kwarg, but instead
    # the filter was silently ignored and we got a IT-user creation
    after = await graphql_client._testing__ituser_read(
        filter=ITUserFilter(employee=EmployeeFilter(uuids=[mo_person])),
    )
    ituser = one(after.objects)
    assert one(ituser.validities).user_key == "from-ldap"
