# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from more_itertools import one
import json
from uuid import UUID
from collections.abc import Awaitable
from collections.abc import Callable
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient

import pytest


@pytest.fixture
async def get_registration_count(
    graphql_client: GraphQLClient,
    mo_person: UUID
) -> Callable[[], Awaitable[int]]:
    async def inner() -> int:
        result = await graphql_client.read_employee_registrations(mo_person)
        employee = one(result.objects)
        return len(employee.registrations)
    return inner


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Employee": {
                        "objectClass": "Employee",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["employeeNumber", "givenName", "sn"],
                        "uuid": "{{ employee_uuid or '' }}",  # TODO: why is this required?
                        "cpr_number": "{{ ldap.employeeNumber }}",
                        "given_name": "{{ ldap.givenName }}",
                        "surname": "{{ ldap.sn }}",
                        "nickname_given_name": "foo",
                        "nickname_surname": "bar",
                    },
                },
                # TODO: why is this required?
                "username_generator": {
                    "combinations_to_try": ["FFFX", "LLLX"],
                },
            }
        ),
    }
)
async def test_no_registration_spam(
    trigger_ldap_person: Callable[[], Awaitable[None]],
    get_registration_count: Callable[[], Awaitable[int]],
) -> None:
    assert await get_registration_count() == 1

    await trigger_ldap_person()

    assert await get_registration_count() == 2

    await trigger_ldap_person()

    assert await get_registration_count() == 2
