# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from typing import Any
from unittest.mock import ANY
from uuid import UUID

import pytest
from more_itertools import one

from mo_ldap_import_export import models
from mo_ldap_import_export.autogenerated_graphql_client import EmployeeUpdateInput
from mo_ldap_import_export.autogenerated_graphql_client import EngagementCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import EngagementFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.moapi import MOAPI
from mo_ldap_import_export.models import Engagement
from mo_ldap_import_export.models import Validity


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Employee": {
                        "objectClass": "Employee",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["employeeNumber", "givenName", "sn"],
                        "uuid": "{{ employee_uuid or '' }}",  # TODO: why is this required?
                        "cpr_number": "{{ ldap.employeeNumber }}",
                        "given_name": "{{ ldap.givenName }}",
                        "surname": "{{ ldap.sn }}",
                    },
                },
                # TODO: why is this required?
                "username_generator": {
                    "combinations_to_try": ["FFFX", "LLLX"],
                },
            }
        ),
    }
)
async def test_employee_patch_semantics(
    graphql_client: GraphQLClient,
    assert_mo_person: Callable[[dict[str, Any]], Awaitable[None]],
    assert_ldap_person: Callable[[dict[str, Any]], Awaitable[None]],
    trigger_ldap_person: Callable[[], Awaitable[None]],
    mo_person: UUID,
) -> None:
    # Assert our starting state in both MO and LDAP
    await assert_mo_person(
        {
            "uuid": ANY,
            "user_key": ANY,
            "cpr_number": "2108613133",
            "given_name": "Aage",
            "surname": "Bach Klarskov",
            "nickname_given_name": "",
            "nickname_surname": "",
        }
    )
    await assert_ldap_person(
        {
            "uid": ["abk"],
            "cn": ["Aage Bach Klarskov"],
            "givenName": ["Aage"],
            "sn": ["Bach Klarskov"],
            "employeeNumber": "2108613133",
            "carLicense": [],
            "displayName": [],
        }
    )

    # Update MO with a new name and nickname
    # Name is owned by LDAP and as such should be overwritten while nickname should not
    cpr = "2108613133"
    await graphql_client._testing__person_update(
        input=EmployeeUpdateInput(
            uuid=mo_person,
            validity=RAValidityInput(from_="2011-12-13T14:15:16Z"),
            # TODO: why is this required?
            cpr_number=cpr,
            # These two fields should be overwritten
            given_name="to be overwritten",
            surname="very soon",
            # These two fields should be kept as-is
            nickname_given_name="Manu",
            nickname_surname="Muster",
        )
    )
    await assert_mo_person(
        {
            "uuid": ANY,
            "user_key": ANY,
            "cpr_number": "2108613133",
            "given_name": "to be overwritten",
            "surname": "very soon",
            "nickname_given_name": "Manu",
            "nickname_surname": "Muster",
        }
    )

    # Force a sync to get trigger the LDAP synchronization
    await trigger_ldap_person()
    await assert_mo_person(
        {
            "uuid": ANY,
            "user_key": ANY,
            "cpr_number": "2108613133",
            # This was modified back
            "given_name": "Aage",
            "surname": "Bach Klarskov",
            # This was kept as-is
            "nickname_given_name": "Manu",
            "nickname_surname": "Muster",
        }
    )


@pytest.mark.integration_test
@pytest.mark.parametrize(
    "extension_1,expected",
    (
        (models.UNSET, "initial"),
        (None, None),
        ("foo", "foo"),
    ),
)
async def test_moapi_edit_engagement_extensions_patch_logic(
    graphql_client: GraphQLClient,
    mo_api: MOAPI,
    mo_person: UUID,
    mo_org_unit: UUID,
    jurist: UUID,
    ansat: UUID,
    extension_1: str | None,
    expected: str | None,
) -> None:
    create = await graphql_client.engagement_create(
        input=EngagementCreateInput(
            person=mo_person,
            org_unit=mo_org_unit,
            job_function=jurist,
            engagement_type=ansat,
            extension_1="initial",
            validity=RAValidityInput(
                from_=datetime(2000, 1, 1),
            ),
        )
    )
    engagement_uuid = create.uuid

    await mo_api.edit_engagement(
        obj=Engagement(
            uuid=engagement_uuid,
            user_key="user_key",
            person=mo_person,
            org_unit=mo_org_unit,
            job_function=jurist,
            engagement_type=ansat,
            primary=None,
            extension_1=extension_1,
            validity=Validity(
                start=datetime(2020, 1, 1),
                end=None,
            ),
        )
    )

    result = await graphql_client.read_engagements(
        EngagementFilter(uuids=[engagement_uuid])
    )
    engagement = one(result.objects)
    assert one(engagement.validities).extension_1 == expected
