# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
import json
import pytest
from fastramqpi.pytest_util import retry
from httpx import AsyncClient
from ldap3 import Connection
from more_itertools import one
from typing import Any
from unittest.mock import ANY
from uuid import UUID

from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.ldap import ldap_add
from mo_ldap_import_export.ldap import ldap_modify
from mo_ldap_import_export.ldap import ldap_search
from mo_ldap_import_export.moapi import MOAPI
from mo_ldap_import_export.utils import combine_dn_strings
from mo_ldap_import_export.utils import mo_today


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "True",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Employee": {
                        "objectClass": "ramodels.mo.employee.Employee",
                        "_import_to_mo_": "true",
                        "_mapper_": "{{ obj.cpr_no }}",
                        "uuid": "{{ employee_uuid or NONE }}",  # TODO: why is this required?
                        "cpr_no": "{{ ldap.employeeNumber }}",
                        "givenname": "{{ ldap.givenName }}",
                        "surname": "{{ ldap.sn }}",
                        "nickname_givenname": "foo",
                        "nickname_surname": "bar",
                    },
                },
                # TODO: why is this required?
                "mo_to_ldap": {
                    "Employee": {
                        "objectClass": "inetOrgPerson",
                        "_export_to_ldap_": "false",
                        "employeeNumber": "{{ mo_employee.cpr_no }}",
                        "givenName": "unused",
                        "sn": "unused",
                    },
                },
                # TODO: why is this required?
                "username_generator": {
                    "objectClass": "UserNameGenerator",
                    "combinations_to_try": ["FFFX", "LLLX"],
                },
            }
        ),
    }
)
async def test_to_mo(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_org_unit: UUID,
    ldap_connection: Connection,
    ldap_org: list[str],
) -> None:
    cpr = "2108613133"

    @retry()
    async def assert_employee(expected: dict) -> None:
        employees = await graphql_client._testing__employee_read(
            filter=EmployeeFilter(cpr_numbers=[cpr])
        )
        employee = one(employees.objects)
        validities = one(employee.validities)
        assert validities.dict() == expected

    person_dn = combine_dn_strings(["uid=abk"] + ldap_org)

    # LDAP: Create
    given_name = "create"
    await ldap_add(
        ldap_connection,
        dn=person_dn,
        object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
        attributes={
            "objectClass": ["top", "person", "organizationalPerson", "inetOrgPerson"],
            "ou": "os2mo",
            "cn": "Aage Bach Klarskov",
            "sn": "Bach Klarskov",
            "employeeNumber": cpr,
            "givenName": given_name,
        },
    )
    # TODO
    response, _ = await ldap_search(
        ldap_connection,
        search_base=combine_dn_strings(ldap_org),
        search_filter=f"(employeeNumber={cpr})",
        attributes=["*"],
    )
    print("LDAP_SEARCH AFTER CREATE", one(response)["attributes"])

    # result = await test_client.get(f"/Inspect/dn2uuid/{person_dn}")
    # assert result.status_code == 200
    # content = result.json()
    # headers = {"Content-Type": "text/plain"}
    # result = await test_client.post("/ldap2mo/uuid", content=content, headers=headers)
    # assert result.status_code == 200

    # TODO
    mo_employee = {
        "uuid": ANY,
        "user_key": ANY,
        "cpr_number": cpr,
        "given_name": given_name,
        "surname": "Bach Klarskov",
        "nickname_given_name": "foo",
        "nickname_surname": "bar",
    }
    await assert_employee(mo_employee)

    # TODO: den kan ikke uploade edited employee fordi data mangler
    # TODO: hvorfor mangler data? fordi

    # LDAP: Edit
    given_name = "edit"
    await ldap_modify(
        ldap_connection,
        dn=person_dn,
        changes={
            "givenName": [("MODIFY_REPLACE", given_name)],
        },
    )
    # TODO
    response, _ = await ldap_search(
        ldap_connection,
        search_base=combine_dn_strings(ldap_org),
        search_filter=f"(employeeNumber={cpr})",
        attributes=["*"],
    )
    print("LDAP_SEARCH AFTER EDIT", one(response)["attributes"])

    # result = await test_client.get(f"/Inspect/dn2uuid/{person_dn}")
    # assert result.status_code == 200
    # content = result.json()
    # headers = {"Content-Type": "text/plain"}
    # result = await test_client.post("/ldap2mo/uuid", content=content, headers=headers)
    # assert result.status_code == 200

    # TODO
    mo_employee = {
        **mo_employee,
        "given_name": given_name,
    }
    await assert_employee(mo_employee)


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "True",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                # TODO: why is this required?
                "ldap_to_mo": {
                    "Employee": {
                        "objectClass": "ramodels.mo.employee.Employee",
                        "_import_to_mo_": "false",
                        "uuid": "{{ employee_uuid or NONE }}",
                        "cpr_no": "{{ldap.employeeNumber}}",
                    },
                },
                "mo_to_ldap": {
                    "Employee": {
                        "objectClass": "inetOrgPerson",
                        "_export_to_ldap_": "true",
                        "employeeNumber": "{{mo_employee.cpr_no}}",
                    },
                },
                # TODO: why is this required?
                "username_generator": {
                    "objectClass": "UserNameGenerator",
                    "combinations_to_try": ["FFFX", "LLLX"],
                },
            }
        ),
    }
)
async def test_to_ldap(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_api: MOAPI,
    mo_person: UUID,
    mo_org_unit: UUID,
    ldap_connection: Connection,
    ldap_org: list[str],
) -> None:
    cpr = "2108613133"

    @retry()
    async def assert_employee(expected: dict[str, Any]) -> None:
        response, _ = await ldap_search(
            ldap_connection,
            search_base=combine_dn_strings(ldap_org),
            search_filter=f"(employeeNumber={cpr})",
            attributes=["title", "departmentNumber"],
        )
        assert one(response)["attributes"] == expected

    # LDAP: Init user
    person_dn = combine_dn_strings(["uid=abk"] + ldap_org)
    await ldap_add(
        ldap_connection,
        dn=person_dn,
        object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
        attributes={
            "objectClass": ["top", "person", "organizationalPerson", "inetOrgPerson"],
            "ou": "os2mo",
            "cn": "Aage Bach Klarskov",
            "sn": "Bach Klarskov",
            "employeeNumber": cpr,
        },
    )
    await assert_employee({"title": [], "departmentNumber": []})

    # MO: Create
    ansat = one(
        (
            await graphql_client.read_class_uuid_by_facet_and_class_user_key(
                "employee_type", "Ansat"
            )
        ).objects
    ).uuid
    jurist = one(
        (
            await graphql_client.read_class_uuid_by_facet_and_class_user_key(
                "employee_job_function", "Jurist"
            )
        ).objects
    ).uuid
    primary = one(
        (
            await graphql_client.read_class_uuid_by_facet_and_class_user_key(
                "primary_type", "primary"
            )
        ).objects
    ).uuid

    title = "create"
    mo_employee = await graphql_client._testing_employee_create(
        input=EmployeeCreateInput(
            user_key=title,
            person=mo_person,
            org_unit=mo_org_unit,
            employee_type=ansat,
            job_function=jurist,
            primary=primary,
            extension_1=title,
            validity={"from": "2001-02-03T04:05:06Z"},
        )
    )
    await assert_employee({"title": [title], "departmentNumber": [str(mo_org_unit)]})

    # MO: Edit
    title = "update"
    await graphql_client._testing_employee_update(
        input=EmployeeUpdateInput(
            uuid=mo_employee.uuid,
            user_key=title,
            validity={"from": "2011-12-13T14:15:16Z"},
            # TODO: why is this required?
            person=mo_person,
            org_unit=mo_org_unit,
            employee_type=ansat,
            job_function=jurist,
            primary=primary,
            extension_1=title,
        )
    )
    await assert_employee({"title": [title], "departmentNumber": [str(mo_org_unit)]})

    # MO: Terminate
    await graphql_client._testing_employee_terminate(
        uuid=mo_employee.uuid,
        to=mo_today(),
    )
    await assert_employee({"title": [], "departmentNumber": []})
