# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections.abc import Awaitable
from collections.abc import Callable
from typing import TypeAlias
from uuid import UUID

import pytest
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client.client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ListenerCreateInput,
)
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.types import LDAPUUID
from mo_ldap_import_export.utils import combine_dn_strings
from tests.integration.conftest import AddLdapPerson
from tests.integration.conftest import DNList2UUID

DeclareListener: TypeAlias = Callable[[str], Awaitable[UUID]]
EmittedUUIDs: TypeAlias = Callable[[UUID], Awaitable[set[LDAPUUID]]]
EmitSubtree: TypeAlias = Callable[..., Awaitable[set[LDAPUUID]]]


@pytest.fixture
async def declare_listener(graphql_client: GraphQLClient) -> DeclareListener:
    async def inner(user_key: str) -> UUID:
        listener = await graphql_client.declare_event_listener(
            input=ListenerCreateInput(
                namespace="ldap",
                routing_key="uuid",
                user_key=user_key,
            )
        )
        return listener.uuid

    return inner


@pytest.fixture
async def emitted_uuids(graphql_client: GraphQLClient) -> EmittedUUIDs:
    async def inner(listener_uuid: UUID) -> set[LDAPUUID]:
        events = await graphql_client.list_events(listener_uuid)
        return {LDAPUUID(e.subject) for e in events.objects}

    return inner


@pytest.fixture
async def emit_subtree(test_client: AsyncClient) -> EmitSubtree:
    async def inner(search_base: str, **params: str | bool) -> set[LDAPUUID]:
        result = await test_client.request(
            "GET",
            "/ldap_event_generator/since",
            content=search_base,
            headers={"Content-Type": "text/plain"},
            params=params,
        )
        assert result.status_code == 200, result.text
        return {LDAPUUID(u) for u in result.json()}

    return inner


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
    }
)
async def test_changed_since(emit_subtree: EmitSubtree, ldap_person_uuid: UUID) -> None:
    base = "ou=os2mo,o=magenta,dc=magenta,dc=dk"
    # A `since` predating the person returns it.
    assert await emit_subtree(base, since="2000-01-01T00:00:00Z") == {ldap_person_uuid}
    # A `since` postdating the person excludes it.
    assert await emit_subtree(base, since="2100-01-01T00:00:00Z") == set()


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LDAP_DIALECT": "AD",
        "LDAP_EVENT_GENERATOR_TYPE": "dirsync",
    }
)
async def test_changed_since_rejected_with_dirsync(
    test_client: AsyncClient,
) -> None:
    result = await test_client.request(
        "GET",
        "/ldap_event_generator/since",
        content="ou=os2mo,o=magenta,dc=magenta,dc=dk",
        headers={"Content-Type": "text/plain"},
    )
    assert result.status_code == 501
    assert result.json()["detail"] == (
        "This endpoint is not supported with the DirSync event generator"
    )


@pytest.mark.integration_test
@pytest.mark.envvar(
    {"LISTEN_TO_CHANGES_IN_MO": "False", "LISTEN_TO_CHANGES_IN_LDAP": "False"}
)
async def test_changed_since_pagination(
    emit_subtree: EmitSubtree,
    add_ldap_person: AddLdapPerson,
    ldap_api: LDAPAPI,
) -> None:
    uuids = set()
    for x in range(2000):
        ldap_person = await add_ldap_person(str(x), "010170" + str(x).rjust(4, "0"))
        person_dn = combine_dn_strings(ldap_person)
        uuids.add(await ldap_api.get_ldap_unique_ldap_uuid(person_dn))

    returned = await emit_subtree(
        "ou=os2mo,o=magenta,dc=magenta,dc=dk", since="2000-01-01T00:00:00Z"
    )
    assert returned == uuids


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
    }
)
@pytest.mark.parametrize("dry_run", [True, False])
async def test_emit_subtree(
    declare_listener: DeclareListener,
    emitted_uuids: EmittedUUIDs,
    emit_subtree: EmitSubtree,
    add_ldap_person: AddLdapPerson,
    dnlist2uuid: DNList2UUID,
    ldap_org_unit: list[str],
    dry_run: bool,
) -> None:
    """The UUIDs are always returned; events are emitted only when not dry-running."""
    listener_uuid = await declare_listener("test_emit_subtree")

    person1 = await add_ldap_person("alice", "0101011234")
    person2 = await add_ldap_person("bob", "0202022345")
    expected = {await dnlist2uuid(person1), await dnlist2uuid(person2)}

    returned = await emit_subtree(combine_dn_strings(ldap_org_unit), dry_run=dry_run)
    assert returned == expected

    emitted = await emitted_uuids(listener_uuid)
    assert emitted == (set() if dry_run else expected)


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
    }
)
async def test_emit_is_subtree_scoped(
    declare_listener: DeclareListener,
    emitted_uuids: EmittedUUIDs,
    emit_subtree: EmitSubtree,
    write_ldap_api: LDAPAPI,
    add_ldap_person: AddLdapPerson,
    dnlist2uuid: DNList2UUID,
    ldap_org: list[str],
    ldap_org_unit: list[str],
) -> None:
    """Only objects at or below the given DN are queued; siblings are excluded."""
    listener_uuid = await declare_listener("test_emit_scoped")

    # Inside the targeted subtree (ou=os2mo).
    inside = await add_ldap_person("dave", "0404044567")
    inside_uuid = await dnlist2uuid(inside)

    # A sibling subtree (ou=other) that must NOT be queued.
    other_ou = ["ou=other"] + ldap_org
    await write_ldap_api.ldap_connection.ldap_add(
        combine_dn_strings(other_ou),
        object_class=["top", "organizationalUnit"],
        attributes={"objectClass": ["top", "organizationalUnit"], "ou": "other"},
    )
    outside = ["uid=erin"] + other_ou
    await write_ldap_api.ldap_connection.ldap_add(
        combine_dn_strings(outside),
        object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
        attributes={
            "objectClass": ["top", "person", "organizationalPerson", "inetOrgPerson"],
            "uid": "erin",
            "cn": "cn",
            "givenName": "givenName",
            "sn": "sn",
            "employeeNumber": "0505055678",
        },
    )

    returned = await emit_subtree(combine_dn_strings(ldap_org_unit), dry_run=False)
    assert returned == {inside_uuid}

    assert await emitted_uuids(listener_uuid) == {inside_uuid}
