# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import Awaitable
from collections.abc import Callable
from typing import Any
from uuid import UUID

import pytest
from fastramqpi.pytest_util import retrying
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import ITUserFilter
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    EmployeeFilter,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    EngagementCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITSystemFilter,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RAValidityInput,
)
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.types import LDAPUUID
from mo_ldap_import_export.utils import combine_dn_strings
from tests.integration.conftest import DN2UUID


ENGAGEMENTS_TEMPLATE = """
{%- set person_uuid = get_person_uuid({'cpr_numbers': [ldap.employeeNumber]}) -%}
{%- set all_engs = load_mo_employee_engagements(person_uuid) -%}
{%- if ldap.carLicense -%}
  {%- set engs = all_engs | selectattr('user_key', 'equalto', ldap.carLicense) | list -%}
{%- else -%}
  {%- set claimed = get_claimed_engagement_uuids(person_uuid, 'ADtitle') -%}
  {%- set engs = all_engs | rejectattr('uuid', 'in', claimed) | list -%}
{%- endif -%}
{{ engs | map(attribute='uuid') | map('string') | list | tojson }}
""".strip()

CONVERSION_MAPPING = json.dumps(
    {
        "ldap_to_mo_any": {
            "inetOrgPerson": [
                {
                    "objectClass": "ITUser",
                    "_import_to_mo_": "true",
                    "_ldap_attributes_": ["carLicense", "employeeNumber"],
                    "_terminate_": "",
                    "uuid": (
                        "{{ get_ituser_uuid({"
                        "  'itsystem': {'user_keys': ['ADtitle']},"
                        "  'employee': {'cpr_numbers': [ldap.employeeNumber]},"
                        "  'user_keys': [ldap.dn],"
                        "  'from_date': None,"
                        "  'to_date': None"
                        "}) or '' }}"
                    ),
                    "user_key": "{{ ldap.dn }}",
                    "person": "{{ get_person_uuid({'cpr_numbers': [ldap.employeeNumber]}) }}",
                    "itsystem": "{{ get_it_system_uuid('ADtitle') }}",
                    "engagements": ENGAGEMENTS_TEMPLATE,
                },
            ],
        },
        "username_generator": {
            "combinations_to_try": ["FFFX", "LLLX"],
        },
    }
)


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": CONVERSION_MAPPING,
    }
)
async def test_ituser_engagement_from_ldap(
    graphql_client: GraphQLClient,
    mo_person: UUID,
    mo_org_unit: UUID,
    ansat: UUID,
    jurist: UUID,
    primary: UUID,
    ldap_api: LDAPAPI,
    ldap_org_unit: list[str],
    trigger_ldap_sync: Callable[[LDAPUUID], Awaitable[None]],
    dn2uuid: DN2UUID,
    adtitle: UUID,
) -> None:
    cpr = "2108613133"

    # --- Setup: Create 3 engagements with distinct user_keys ---
    eng1 = await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key="eng1",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity=RAValidityInput(from_="1970-01-01T00:00:00"),
        )
    )
    eng2 = await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key="eng2",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity=RAValidityInput(from_="1970-01-01T00:00:00"),
        )
    )
    eng3 = await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key="eng3",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity=RAValidityInput(from_="1970-01-01T00:00:00"),
        )
    )

    # --- Setup: Create 2 LDAP accounts with same CPR ---
    # Account 1: has carLicense matching eng1's user_key
    account1_dn_parts = ["uid=account1"] + ldap_org_unit
    await ldap_api.ldap_connection.ldap_add(
        dn=combine_dn_strings(account1_dn_parts),
        object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
        attributes={
            "objectClass": ["top", "person", "organizationalPerson", "inetOrgPerson"],
            "ou": "os2mo",
            "cn": "Aage Bach Klarskov",
            "sn": "Bach Klarskov",
            "employeeNumber": cpr,
            "carLicense": "eng1",
        },
    )
    account1_dn = combine_dn_strings(account1_dn_parts)
    account1_uuid = await dn2uuid(account1_dn)

    # Account 2: no carLicense
    account2_dn_parts = ["uid=account2"] + ldap_org_unit
    await ldap_api.ldap_connection.ldap_add(
        dn=combine_dn_strings(account2_dn_parts),
        object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
        attributes={
            "objectClass": ["top", "person", "organizationalPerson", "inetOrgPerson"],
            "ou": "os2mo",
            "cn": "Aage Bach Klarskov",
            "sn": "Bach Klarskov",
            "employeeNumber": cpr,
        },
    )
    account2_dn = combine_dn_strings(account2_dn_parts)
    account2_uuid = await dn2uuid(account2_dn)

    # --- Helper to read IT-users with engagement_uuids ---
    async def get_itusers() -> list[dict[str, Any]]:
        # Step 1: Find IT-user UUIDs via filter
        filtered = await graphql_client.read_filtered_itusers(
            ITUserFilter(
                employee=EmployeeFilter(uuids=[mo_person]),
                itsystem=ITSystemFilter(user_keys=["ADtitle"]),
                from_date=None,
                to_date=None,
            )
        )
        if not filtered.objects:
            return []
        uuids = [one(obj.validities).uuid for obj in filtered.objects]
        # Step 2: Read full details including engagement_uuids
        result = await graphql_client.read_itusers(
            uuids, from_date=None, to_date=None
        )
        return [
            {
                "user_key": one(obj.validities).user_key,
                "engagement_uuids": sorted(
                    str(u) for u in one(obj.validities).engagement_uuids
                ),
            }
            for obj in result.objects
        ]

    # --- Stage 1: Trigger sync for account 1 (has carLicense=eng1) ---
    await trigger_ldap_sync(account1_uuid)

    async for attempt in retrying():
        with attempt:
            itusers = await get_itusers()
            ituser = one(itusers)
            assert ituser["user_key"] == account1_dn
            assert ituser["engagement_uuids"] == sorted([str(eng1.uuid)])

    # --- Stage 2: Trigger sync for account 2 (no carLicense) ---
    await trigger_ldap_sync(account2_uuid)

    async for attempt in retrying():
        with attempt:
            itusers = await get_itusers()
            assert len(itusers) == 2
            ituser_map = {it["user_key"]: it["engagement_uuids"] for it in itusers}
            assert ituser_map[account1_dn] == sorted([str(eng1.uuid)])
            assert ituser_map[account2_dn] == sorted(
                [str(eng2.uuid), str(eng3.uuid)]
            )
