# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Prove that an engagement-style ldap_to_mo_any mapping using
`find_mo_employee_uuid_by_guid_and_cpr` triggers exactly one LDAP search,
whereas the equivalent mapping using `find_mo_employee_uuid(ldap.dn)` issues
many redundant searches.
"""

import json
from collections.abc import Awaitable
from collections.abc import Callable
from typing import cast
from uuid import UUID

import pytest
from fastramqpi.context import Context
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client import EngagementCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.dataloaders import DataLoader


@pytest.fixture
def dataloader(test_client: AsyncClient, context: Context) -> DataLoader:
    return cast(DataLoader, context["user_context"]["dataloader"])


@pytest.fixture
def ldap_search_counter(
    monkeypatch: pytest.MonkeyPatch, dataloader: DataLoader
) -> Callable[[], int]:
    """Count every LDAP search issued through the running app's connection."""
    state = {"count": 0}
    connection = dataloader.ldapapi.ldap_connection.connection
    original = connection.search

    def counted(*args, **kwargs):
        state["count"] += 1
        return original(*args, **kwargs)

    monkeypatch.setattr(connection, "search", counted)
    return lambda: state["count"]


@pytest.fixture
async def mo_engagement(
    graphql_client: GraphQLClient,
    mo_person: UUID,
    mo_org_unit: UUID,
    ansat: UUID,
    jurist: UUID,
    primary: UUID,
) -> None:
    await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key="engagement",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            extension_1="create",
            validity=RAValidityInput(from_="2001-02-03T04:05:06Z"),
        )
    )


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo_any": {
                    "inetOrgPerson": [
                        {
                            "objectClass": "Engagement",
                            "_import_to_mo_": "true",
                            "_ldap_attributes_": ["title"],
                            "uuid": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid(ldap.dn)
                                      )
                                    )
                                  ).uuid
                                }}
                            """,
                            "user_key": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid(ldap.dn)
                                      )
                                    )
                                  ).user_key
                                }}
                            """,
                            "org_unit": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid(ldap.dn)
                                      )
                                    )
                                  ).org_unit
                                }}
                            """,
                            "person": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid(ldap.dn)
                                      )
                                    )
                                  ).person
                                }}
                            """,
                            "job_function": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid(ldap.dn)
                                      )
                                    )
                                  ).job_function
                                }}
                            """,
                            "engagement_type": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid(ldap.dn)
                                      )
                                    )
                                  ).engagement_type
                                }}
                            """,
                            "primary": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid(ldap.dn)
                                      )
                                    )
                                  ).primary
                                }}
                            """,
                            "extension_1": "{{ ldap.title }}",
                        },
                    ],
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("test_client", "mo_engagement")
async def test_legacy_template_does_many_lookups(
    trigger_ldap_person: Callable[[], Awaitable[None]],
    ldap_search_counter: Callable[[], int],
) -> None:
    await trigger_ldap_person()
    # 1 initial event fetch + 1 uuid pre-lookup (used to find the existing MO
    # object) + 1 search per template field (7 fields use the helper) = 9.
    assert ldap_search_counter() == 9


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo_any": {
                    "inetOrgPerson": [
                        {
                            "objectClass": "Engagement",
                            "_import_to_mo_": "true",
                            "_ldap_attributes_": [
                                "title",
                                "employeeNumber",
                                "entryUUID",
                            ],
                            "uuid": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid_by_guid_and_cpr(
                                          ldap.entryUUID, ldap.employeeNumber
                                        )
                                      )
                                    )
                                  ).uuid
                                }}
                            """,
                            "user_key": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid_by_guid_and_cpr(
                                          ldap.entryUUID, ldap.employeeNumber
                                        )
                                      )
                                    )
                                  ).user_key
                                }}
                            """,
                            "org_unit": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid_by_guid_and_cpr(
                                          ldap.entryUUID, ldap.employeeNumber
                                        )
                                      )
                                    )
                                  ).org_unit
                                }}
                            """,
                            "person": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid_by_guid_and_cpr(
                                          ldap.entryUUID, ldap.employeeNumber
                                        )
                                      )
                                    )
                                  ).person
                                }}
                            """,
                            "job_function": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid_by_guid_and_cpr(
                                          ldap.entryUUID, ldap.employeeNumber
                                        )
                                      )
                                    )
                                  ).job_function
                                }}
                            """,
                            "engagement_type": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid_by_guid_and_cpr(
                                          ldap.entryUUID, ldap.employeeNumber
                                        )
                                      )
                                    )
                                  ).engagement_type
                                }}
                            """,
                            "primary": """
                                {{
                                  skip_if_none(
                                    load_mo_primary_engagement(
                                      skip_if_none(
                                        find_mo_employee_uuid_by_guid_and_cpr(
                                          ldap.entryUUID, ldap.employeeNumber
                                        )
                                      )
                                    )
                                  ).primary
                                }}
                            """,
                            "extension_1": "{{ ldap.title }}",
                        },
                    ],
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("test_client", "mo_engagement")
async def test_migrated_template_does_one_lookup(
    trigger_ldap_person: Callable[[], Awaitable[None]],
    ldap_search_counter: Callable[[], int],
) -> None:
    await trigger_ldap_person()
    assert ldap_search_counter() == 1
