# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""LDAP->MO edits should only update the current validity, not clobber others."""

import json
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import date
from typing import Any

import pytest
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import EngagementCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import EngagementFilter
from mo_ldap_import_export.autogenerated_graphql_client import EngagementUpdateInput
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.types import DN
from mo_ldap_import_export.utils import mo_today

ReadValidities = Callable[[], Awaitable[list[tuple[str, date, date | None]]]]


@pytest.fixture
def read_validities(graphql_client: GraphQLClient, mo_person: Any) -> ReadValidities:
    async def inner() -> list[tuple[str, date, date | None]]:
        engagements = await graphql_client._testing__engagement_read(
            filter=EngagementFilter(
                from_date=None,
                to_date=None,
                employee=EmployeeFilter(uuids=[mo_person]),
            ),
        )
        engagement = one(engagements.objects)
        entries = [
            (
                v.user_key,
                v.validity.from_.date(),
                v.validity.to.date() if v.validity.to is not None else None,
            )
            for v in engagement.validities
        ]
        # Order chronologically by validity start.
        return sorted(entries, key=lambda entry: entry[1])

    return inner


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Engagement": {
                        "objectClass": "Engagement",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["title"],
                        "uuid": "{{ load_mo_primary_engagement(employee_uuid).uuid }}",
                        "user_key": "{{ ldap.title }}",
                        "person": "{{ load_mo_primary_engagement(employee_uuid).person }}",
                        "org_unit": "{{ load_mo_primary_engagement(employee_uuid).org_unit }}",
                        "engagement_type": "{{ load_mo_primary_engagement(employee_uuid).engagement_type }}",
                        "job_function": "{{ load_mo_primary_engagement(employee_uuid).job_function }}",
                        "primary": "{{ load_mo_primary_engagement(employee_uuid).primary }}",
                    },
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("test_client")
async def test_no_terminate_template_preserves_future_validity(
    graphql_client: GraphQLClient,
    mo_person: Any,
    mo_org_unit: Any,
    ansat: Any,
    jurist: Any,
    primary: Any,
    trigger_ldap_person: Callable[[], Awaitable[None]],
    read_validities: ReadValidities,
) -> None:
    """Without a _terminate_ template, only the current validity is updated."""
    # Seed: [2001, 2030]="past", [2030, 2040]="future".
    created = await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key="past",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity=RAValidityInput(
                from_="2001-02-03T00:00:00Z", to="2040-01-01T00:00:00Z"
            ),
        )
    )
    await graphql_client.engagement_update(
        input=EngagementUpdateInput(
            uuid=created.uuid,
            user_key="future",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity=RAValidityInput(
                from_="2030-01-01T00:00:00Z", to="2040-01-01T00:00:00Z"
            ),
        )
    )

    # Before the sync.
    assert await read_validities() == [
        ("past", date(2001, 2, 3), date(2030, 1, 1)),
        ("future", date(2030, 1, 1), date(2040, 1, 1)),
    ]

    await trigger_ldap_person()

    today = mo_today().date()
    assert await read_validities() == [
        ("past", date(2001, 2, 3), today),
        ("Skole underviser", today, date(2030, 1, 1)),
        ("future", date(2030, 1, 1), date(2040, 1, 1)),
    ]


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Engagement": {
                        "objectClass": "Engagement",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["carLicense", "title"],
                        "_terminate_": "{{ ldap.carLicense }}",
                        "uuid": "{{ load_mo_primary_engagement(employee_uuid).uuid }}",
                        "user_key": "{{ ldap.title }}",
                        "person": "{{ load_mo_primary_engagement(employee_uuid).person }}",
                        "org_unit": "{{ load_mo_primary_engagement(employee_uuid).org_unit }}",
                        "engagement_type": "{{ load_mo_primary_engagement(employee_uuid).engagement_type }}",
                        "job_function": "{{ load_mo_primary_engagement(employee_uuid).job_function }}",
                        "primary": "{{ load_mo_primary_engagement(employee_uuid).primary }}",
                    },
                },
            }
        ),
    }
)
@pytest.mark.parametrize(
    "car_license, expected",
    [
        # Matches the final end-date: only the current validity updates, future kept.
        pytest.param(
            "2040-01-01",
            lambda today: [
                ("past", date(2001, 2, 3), today),
                ("Skole underviser", today, date(2030, 1, 1)),
                ("future", date(2030, 1, 1), date(2040, 1, 1)),
            ],
            id="equal-to-final-end-keeps-future",
        ),
        # Differs from the final end-date: terminated there, future removed.
        pytest.param(
            "2035-01-01",
            lambda today: [
                ("past", date(2001, 2, 3), today),
                ("Skole underviser", today, date(2035, 1, 1)),
            ],
            id="before-final-end-terminates",
        ),
    ],
)
@pytest.mark.usefixtures("test_client")
async def test_terminate(
    car_license: str,
    expected: Callable[[date], list[tuple[str, date, date | None]]],
    graphql_client: GraphQLClient,
    mo_person: Any,
    mo_org_unit: Any,
    ansat: Any,
    jurist: Any,
    primary: Any,
    ldap_api: LDAPAPI,
    ldap_person_dn: DN,
    trigger_ldap_person: Callable[[], Awaitable[None]],
    read_validities: ReadValidities,
) -> None:
    """_terminate_ matching the final end-date only updates the current validity;
    a differing date terminates the engagement there."""
    # Seed: [2001, 2030]="past", [2030, 2040]="future".
    created = await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key="past",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity=RAValidityInput(
                from_="2001-02-03T00:00:00Z", to="2040-01-01T00:00:00Z"
            ),
        )
    )
    await graphql_client.engagement_update(
        input=EngagementUpdateInput(
            uuid=created.uuid,
            user_key="future",
            person=mo_person,
            org_unit=mo_org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity=RAValidityInput(
                from_="2030-01-01T00:00:00Z", to="2040-01-01T00:00:00Z"
            ),
        )
    )

    # Before the sync.
    assert await read_validities() == [
        ("past", date(2001, 2, 3), date(2030, 1, 1)),
        ("future", date(2030, 1, 1), date(2040, 1, 1)),
    ]

    await ldap_api.ldap_connection.ldap_modify(
        ldap_person_dn,
        changes={"carLicense": [("MODIFY_REPLACE", car_license)]},
    )
    await trigger_ldap_person()

    assert await read_validities() == expected(mo_today().date())
