# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from uuid import UUID

import pytest
from more_itertools import one
from structlog.testing import capture_logs

from mo_ldap_import_export.autogenerated_graphql_client import AddressCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import AddressFilter
from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.autogenerated_graphql_client._testing__address_read import (
    TestingAddressReadAddressesObjectsValidities,
)
from mo_ldap_import_export.autogenerated_graphql_client._testing__address_registration import (
    TestingAddressRegistrationAddressesObjectsRegistrations,
)

ENVVAR = {
    "LISTEN_TO_CHANGES_IN_MO": "False",
    "LISTEN_TO_CHANGES_IN_LDAP": "False",
    "CONVERSION_MAPPING": json.dumps(
        {
            "ldap_to_mo": {
                "EmailEmployee": {
                    "objectClass": "Address",
                    "_import_to_mo_": "true",
                    "_ldap_attributes_": [],
                    # All values are static, nothing but validity will change between syncs
                    "uuid": """
                    {{
                        get_address_uuid({
                            "address_type": {"user_keys": ["EmailEmployee"]},
                            "employee": {"uuids": [employee_uuid]}
                        })
                    }}
                    """,
                    "user_key": "-",
                    "value": "noop@example.org",
                    "address_type": "{{ get_employee_address_type_uuid('EmailEmployee') }}",
                    "person": "{{ employee_uuid }}",
                },
            },
        }
    ),
}


@pytest.fixture
async def get_address_registrations(
    graphql_client: GraphQLClient,
) -> Callable[
    [UUID], Awaitable[list[TestingAddressRegistrationAddressesObjectsRegistrations]]
]:
    async def inner(
        address_uuid: UUID,
    ) -> list[TestingAddressRegistrationAddressesObjectsRegistrations]:
        result = await graphql_client._testing__address_registration(
            filter=AddressFilter(uuids=[address_uuid]),
        )
        return one(result.objects).registrations

    return inner


@pytest.fixture
async def get_mo_person_address_validities(
    graphql_client: GraphQLClient, mo_person: UUID
) -> Callable[[], Awaitable[list[TestingAddressReadAddressesObjectsValidities]]]:
    async def inner() -> list[TestingAddressReadAddressesObjectsValidities]:
        addresses = await graphql_client._testing__address_read(
            filter=AddressFilter(
                employee=EmployeeFilter(uuids=[mo_person]),
                from_date=None,
                to_date=None,
            ),
        )
        return one(addresses.objects).validities

    return inner


@pytest.mark.integration_test
@pytest.mark.envvar(ENVVAR)
@pytest.mark.usefixtures("test_client")
async def test_same_day_sync_is_noop(
    trigger_ldap_person: Callable[[], Awaitable[None]],
    get_mo_person_address_validities: Callable[
        [], Awaitable[list[TestingAddressReadAddressesObjectsValidities]]
    ],
    get_address_registrations: Callable[
        [UUID], Awaitable[list[TestingAddressRegistrationAddressesObjectsRegistrations]]
    ],
) -> None:
    """Synchronizing twice on the same day produce a single validity and registration.

    As both synchronizations get the same validity.start (`mo_today()`) only a single
    write is made to OS2mo, as the other write hits the:

    * Converted object is identical to existing object, skipping

    Case within the LDAP to MO code, thus only a single write happens to OS2mo, and thus
    only a single validity and a single registration is produced.
    """
    # First sync creates the address, single registration, single validity
    await trigger_ldap_person()
    validity_before = one(await get_mo_person_address_validities())
    reg_before = one(await get_address_registrations(validity_before.uuid))

    # Second sync is a noop since the change is within the same day in MO
    with capture_logs() as cap_logs:
        await trigger_ldap_person()
    assert "Converted object is identical to existing object, skipping" in [
        x["event"] for x in cap_logs
    ]
    validity_after = one(await get_mo_person_address_validities())
    reg_after = one(await get_address_registrations(validity_after.uuid))

    assert validity_before == validity_after
    assert reg_before == reg_after


@pytest.mark.integration_test
@pytest.mark.envvar(ENVVAR)
@pytest.mark.usefixtures("test_client")
async def test_different_day_sync_is_kinda_noop(
    graphql_client: GraphQLClient,
    mo_person: UUID,
    email_employee: UUID,
    trigger_ldap_person: Callable[[], Awaitable[None]],
    get_mo_person_address_validities: Callable[
        [], Awaitable[list[TestingAddressReadAddressesObjectsValidities]]
    ],
    get_address_registrations: Callable[
        [UUID], Awaitable[list[TestingAddressRegistrationAddressesObjectsRegistrations]]
    ],
) -> None:
    """Synchronizing across multiple days produces a single validity and registration.

    This test differs from test_same_day_sync_is_noop by emulating changes made across
    multiple days by pre-seeding the address in MO. As such the synchronization call
    gets a different validity.start (`mo_today()`) than what is read from OS2mo, thus
    avoiding the identical object skip, However, since only validity.start changes
    (validity.end is unchanged), the integration detects this situation and does an
    early return, emulating the behavior of the prior test, thereby avoiding adding a
    useless registration to the database.
    """
    # Pre-create the address with a start date in the past to emulate the integration
    # running at some point in the past.
    address = await graphql_client.address_create(
        input=AddressCreateInput(
            # These data match the ones in the ENVVAR CONVERSION_MAPPING
            user_key="-",
            person=mo_person,
            address_type=email_employee,
            value="noop@example.org",
            validity=RAValidityInput(
                from_=datetime(2020, 1, 1),
                to=None,
            ),
        )
    )
    validity_before = one(await get_mo_person_address_validities())
    reg_before = one(await get_address_registrations(address.uuid))

    # 'Second' sync is a noop since only validity.start differs (2020-01-01 vs mo_today)
    # and thus the code early returns.
    with capture_logs() as cap_logs:
        await trigger_ldap_person()
    assert "Converted object contain only validity.start change, skipping" in [
        x["event"] for x in cap_logs
    ]
    validity_after = one(await get_mo_person_address_validities())
    reg_after = one(await get_address_registrations(validity_after.uuid))

    assert validity_before == validity_after
    assert reg_before == reg_after
