# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import pytest
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client.client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ListenerCreateInput,
)
from mo_ldap_import_export.types import LDAPUUID


@pytest.mark.integration_test
async def test_emit_endpoint(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
) -> None:
    """Test that POST /ldap_event_generator/emit/{uuid} emits an event."""
    listener = await graphql_client.declare_event_listener(
        input=ListenerCreateInput(
            namespace="ldap",
            routing_key="uuid",
            user_key="test_emit_endpoint",
        )
    )

    uuid = LDAPUUID("c5471289-a5d0-43fa-a63f-58f23583ee82")
    result = await test_client.post(f"/ldap_event_generator/emit/{uuid}")
    assert result.status_code == 200, result.text

    events = await graphql_client.list_events(listener.uuid)
    uuids = {LDAPUUID(e.subject) for e in events.objects}
    assert uuids == {uuid}
