# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
import random
from collections.abc import Awaitable
from collections.abc import Callable
from unittest.mock import ANY
from uuid import UUID

import pytest
from ldap3 import MODIFY_ADD
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import AddressFilter
from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.types import DN
from mo_ldap_import_export.utils import mo_today
from tests.conftest import construct_mitid_nl3uuid


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "True",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "StringEmployee": {
                        "objectClass": "Address",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["carLicense"],
                        "uuid": "{{ get_address_uuid({'address_type': {'user_key': 'StringEmployee'}, 'employee': {'uuids': [employee_uuid]}}) }}",
                        "value": "{{ ldap.carLicense | extract_mitid_uuid }}",
                        "address_type": "{{ get_employee_address_type_uuid('StringEmployee') }}",
                        "person": "{{ employee_uuid }}",
                        "visibility": "{{ get_visibility_uuid('Public') }}",
                    },
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("test_client")
async def test_mitid_import(
    graphql_client: GraphQLClient,
    mo_person: UUID,
    ldap_api: LDAPAPI,
    ldap_person_dn: DN,
    trigger_ldap_person: Callable[[], Awaitable[None]],
) -> None:
    # Randomly generated UUID
    mitid_uuid = UUID("0d5a38a0-7690-4820-9189-9a64703a95f5")
    alt_sec_id = construct_mitid_nl3uuid(mitid_uuid)

    car_license_values = [
        alt_sec_id,
        "some-other-value",
        "another-random-string",
        "and-one-more",
    ]
    random.shuffle(car_license_values)

    # LDAP: Add carLicense to existing person
    await ldap_api.ldap_connection.ldap_modify(
        dn=ldap_person_dn,
        changes={"carLicense": [(MODIFY_ADD, car_license_values)]},
    )

    await trigger_ldap_person()

    addresses = await graphql_client._testing__address_read(
        filter=AddressFilter(
            employee=EmployeeFilter(uuids=[mo_person]),
        ),
    )
    address = one(addresses.objects)
    assert one(address.validities).dict() == {
        "uuid": ANY,
        "user_key": ANY,
        "address_type": {"user_key": "StringEmployee"},
        "value": str(mitid_uuid),
        "value2": None,
        "person": [{"uuid": mo_person}],
        "visibility": {"user_key": "Public"},
        "validity": {"from_": mo_today(), "to": None},
    }
