# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import Awaitable
from collections.abc import Callable
from uuid import UUID

import pytest
from more_itertools import first
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import AddressFilter
from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.utils import combine_dn_strings


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Employee": {
                        "objectClass": "Employee",
                        "_import_to_mo_": "false",
                        "_ldap_attributes_": [],
                        "uuid": "{{ employee_uuid or '' }}",
                    },
                    "EmailEmployee": {
                        "objectClass": "Address",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["mail"],
                        "_terminate_": "",
                        "uuid": "{{ get_address_uuid({'address_type': {'user_key': 'EmailEmployee'}, 'employee': {'uuids': [employee_uuid]}}) }}",
                        # Here we pick the first value after sorting
                        "value": "{{ ldap.mail | sort | first }}",
                        "address_type": "{{ get_employee_address_type_uuid('EmailEmployee') }}",
                        "person": "{{ employee_uuid }}",
                        "visibility": "{{ get_visibility_uuid('Public') }}",
                    },
                },
                "username_generator": {
                    "combinations_to_try": ["FFFX", "LLLX"],
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("test_client")
async def test_multi_valued_address_from_ldap(
    graphql_client: GraphQLClient,
    mo_person: UUID,
    ldap_api: LDAPAPI,
    ldap_org_unit: list[str],
    trigger_ldap_person: Callable[[], Awaitable[None]],
) -> None:
    person_dn = combine_dn_strings(["uid=abk"] + ldap_org_unit)

    # LDAP: Create with multiple mail values
    mails = ["b@example.com", "a@example.com"]
    sorted_mail = first(sorted(mails))

    await ldap_api.ldap_connection.ldap_modify(
        dn=person_dn,
        changes={
            "mail": [("MODIFY_REPLACE", mails)],
        },
    )

    # Trigger sync from LDAP to MO
    await trigger_ldap_person()

    # Verify that we picked the lowest alphabetical value
    addresses = await graphql_client._testing__address_read(
        filter=AddressFilter(
            employee=EmployeeFilter(uuids=[mo_person]),
        ),
    )
    address = one(addresses.objects)
    assert one(address.validities).value == sorted_mail
