# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from uuid import UUID
from uuid import uuid4

import pytest
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    AddressCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITSystemCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITUserCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RAOpenValidityInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RAValidityInput,
)


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LDAP_IT_SYSTEM": "",
    }
)
@pytest.mark.parametrize("num_itusers", (0, 1, 5))
async def test_delete_all_itusers_for_itsystems(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
    num_itusers: int,
) -> None:
    # Create a deprecated IT-system to be purged
    old_itsystem = await graphql_client.itsystem_create(
        input=ITSystemCreateInput(
            user_key="Skole-AD",
            name="Skole-AD",
            validity=RAOpenValidityInput(from_="1970-01-01T00:00:00Z"),
        )
    )

    # Populate it with a number of IT-users
    ituser_uuids = set()
    for _ in range(num_itusers):
        ituser = await graphql_client.ituser_create(
            ITUserCreateInput(
                person=mo_person,
                user_key=str(uuid4()),
                itsystem=old_itsystem.uuid,
                validity=RAValidityInput(from_="1970-01-01T00:00:00"),
            )
        )
        ituser_uuids.add(str(ituser.uuid))

    # Dry-run: expect to see all the IT-user UUIDs that would be deleted
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        json=["Skole-AD"],
    )
    assert response.status_code == 200
    assert set(response.json()) == ituser_uuids

    # dry_run=False: actually delete them, expecting all the IT-user UUIDs back
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"dry_run": "false"},
        json=["Skole-AD"],
    )
    assert response.status_code == 200
    assert set(response.json()) == ituser_uuids

    # Retest with dry-run: everything should now be gone without a trace
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        json=["Skole-AD"],
    )
    assert response.status_code == 200
    assert response.json() == []


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LDAP_IT_SYSTEM": "",
    }
)
async def test_delete_all_itusers_for_multiple_itsystems(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
) -> None:
    # Create several deprecated IT-systems, each with an IT-user
    expected = set()
    for user_key in ("Skole-AD", "Sprogcenter-AD", "Active Directory GUID"):
        itsystem = await graphql_client.itsystem_create(
            input=ITSystemCreateInput(
                user_key=user_key,
                name=user_key,
                validity=RAOpenValidityInput(from_="1970-01-01T00:00:00Z"),
            )
        )
        ituser = await graphql_client.ituser_create(
            ITUserCreateInput(
                person=mo_person,
                user_key=str(uuid4()),
                itsystem=itsystem.uuid,
                validity=RAValidityInput(from_="1970-01-01T00:00:00"),
            )
        )
        expected.add(str(ituser.uuid))

    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"dry_run": "false"},
        json=["Skole-AD", "Sprogcenter-AD", "Active Directory GUID"],
    )
    assert response.status_code == 200
    assert set(response.json()) == expected


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LDAP_IT_SYSTEM": "",
    }
)
async def test_delete_all_itusers_for_itsystems_unknown_itsystem(
    test_client: AsyncClient,
) -> None:
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        json=["Does-Not-Exist"],
    )
    assert response.status_code == 404


@pytest.fixture
async def itsystem_with_referenced_ituser(
    graphql_client: GraphQLClient,
    mo_person: UUID,
    email_employee: UUID,
    public: UUID,
) -> tuple[UUID, UUID]:
    """Create a deprecated IT-system with an IT-user that has an address scoped to
    it. Returns (ituser_uuid, address_uuid)."""
    itsystem = await graphql_client.itsystem_create(
        input=ITSystemCreateInput(
            user_key="Skole-AD",
            name="Skole-AD",
            validity=RAOpenValidityInput(from_="1970-01-01T00:00:00Z"),
        )
    )
    ituser = await graphql_client.ituser_create(
        ITUserCreateInput(
            person=mo_person,
            user_key=str(uuid4()),
            itsystem=itsystem.uuid,
            validity=RAValidityInput(from_="1970-01-01T00:00:00"),
        )
    )
    address = await graphql_client.address_create(
        input=AddressCreateInput(
            value="test@example.com",
            address_type=email_employee,
            visibility=public,
            person=mo_person,
            ituser=ituser.uuid,
            validity=RAValidityInput(from_="1970-01-01T00:00:00"),
        )
    )
    return ituser.uuid, address.uuid


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LDAP_IT_SYSTEM": "",
    }
)
async def test_dangling_references_for_itsystems(
    test_client: AsyncClient,
    itsystem_with_referenced_ituser: tuple[UUID, UUID],
) -> None:
    _, address_uuid = itsystem_with_referenced_ituser

    response = await test_client.post(
        "/fixup/dangling_references_for_itsystems",
        json=["Skole-AD"],
    )
    assert response.status_code == 200
    assert response.json() == {
        "addresses": [str(address_uuid)],
        "rolebindings": [],
    }


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LDAP_IT_SYSTEM": "",
    }
)
async def test_delete_all_itusers_for_itsystems_aborts_on_dangling(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    itsystem_with_referenced_ituser: tuple[UUID, UUID],
) -> None:
    ituser_uuid, address_uuid = itsystem_with_referenced_ituser

    # Without force the deletion is refused due to the dangling address
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"dry_run": "false"},
        json=["Skole-AD"],
    )
    assert response.status_code == 409
    detail = response.json()["detail"]
    assert detail["dangling_references"]["addresses"] == [str(address_uuid)]

    # The IT-user must still exist (nothing was deleted)
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        json=["Skole-AD"],
    )
    assert response.json() == [str(ituser_uuid)]

    # With force=true the IT-user is deleted despite the dangling reference
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"dry_run": "false", "force": "true"},
        json=["Skole-AD"],
    )
    assert response.status_code == 200
    assert response.json() == [str(ituser_uuid)]
