# SPDX-FileCopyrightText: Viborg kommune <https://viborg.dk/>
# SPDX-License-Identifier: MPL-2.0
import json
from datetime import datetime
from uuid import UUID

import pytest
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    AddressCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITUserCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RAValidityInput,
)
from tests.integration.conftest import AddEngagement

conversion_mapping_with_aduuid_itsystem = {
    "ldap_to_mo": {
        "Employee": {
            "objectClass": "Employee",
            "_import_to_mo_": "false",
            "_ldap_attributes_": [],
            "uuid": "{{ employee_uuid or '' }}",
        },
        "ADUUID": {
            "objectClass": "ITUser",
            "_import_to_mo_": "true",
            "_ldap_attributes_": ["entryUUID"],
            "uuid": "{{ get_ituser_uuid({'itsystem': {'user_keys': ['ADUUID']}, 'employee': {'uuids': [employee_uuid]}}) }}",
            "user_key": "{{ ldap.entryUUID }}",
            "itsystem": "{{ get_it_system_uuid('ADUUID') }}",
            "person": "{{ employee_uuid or '' }}",
        },
        "EmailEmployee": {
            "objectClass": "Address",
            "_import_to_mo_": "true",
            "_ldap_attributes_": ["carLicense", "mail"],
            # carLicense is arbitrarily chosen as an enabled/disabled marker
            "_terminate_": "{{ now()|mo_datestring if ldap.carLicense == 'EXPIRED' else '' }}",
            "uuid": "{{ get_address_uuid({'address_type': {'user_keys': ['EmailEmployee']}, 'employee': {'uuids': [employee_uuid]}}) }}",
            "value": "{{ ldap.mail }}",
            "address_type": "{{ get_employee_address_type_uuid('EmailEmployee') }}",
            "person": "{{ employee_uuid }}",
            "visibility": "{{ get_visibility_uuid('Public') }}",
        },
        "MitIDEmployee": {
            "objectClass": "Address",
            "_import_to_mo_": "true",
            "_ldap_attributes_": ["carLicense", "mail"],
            # carLicense is arbitrarily chosen as an enabled/disabled marker
            "_terminate_": "{{ now()|mo_datestring if ldap.carLicense == 'EXPIRED' else '' }}",
            "uuid": "{{ get_address_uuid({'address_type': {'user_keys': ['PhoneEmployee']}, 'employee': {'uuids': [employee_uuid]}}) }}",
            "value": "{{ ldap.mobile }}",
            "address_type": "{{ get_employee_address_type_uuid('PhoneEmployee') }}",
            "person": "{{ employee_uuid }}",
            "visibility": "{{ get_visibility_uuid('Public') }}",
        },
        "PhoneEmployee": {
            "objectClass": "Address",
            "_import_to_mo_": "true",
            "_ldap_attributes_": ["carLicense", "mail"],
            # carLicense is arbitrarily chosen as an enabled/disabled marker
            "_terminate_": "{{ now()|mo_datestring if ldap.carLicense == 'EXPIRED' else '' }}",
            "uuid": "{{ get_address_uuid({'address_type': {'user_keys': ['MitIDEmployee']}, 'employee': {'uuids': [employee_uuid]}}) }}",
            "value": "{{ ldap.altSecurityIdentities }}",
            "address_type": "{{ get_employee_address_type_uuid('MitIDEmployee') }}",
            "person": "{{ employee_uuid }}",
            "visibility": "{{ get_visibility_uuid('Public') }}",
        },
        "MobileEmployee": {
            "objectClass": "Address",
            "_import_to_mo_": "true",
            "_ldap_attributes_": ["carLicense", "mail"],
            # carLicense is arbitrarily chosen as an enabled/disabled marker
            "_terminate_": "{{ now()|mo_datestring if ldap.carLicense == 'EXPIRED' else '' }}",
            "uuid": "{{ get_address_uuid({'address_type': {'user_keys': ['MobileEmployee']}, 'employee': {'uuids': [employee_uuid]}}) }}",
            "value": "{{ ldap.mobile }}",
            "address_type": "{{ get_employee_address_type_uuid('MobileEmployee') }}",
            "person": "{{ employee_uuid }}",
            "visibility": "{{ get_visibility_uuid('Public') }}",
        },
        "PagerEmployee": {
            "objectClass": "Address",
            "_import_to_mo_": "true",
            "_ldap_attributes_": ["pager"],
            "uuid": "{{ get_address_uuid({'address_type': {'user_keys': ['PagerEmployee']}, 'employee': {'uuids': [employee_uuid]}}) }}",
            "value": "{{ ldap.pager }}",
            "address_type": "{{ get_employee_address_type_uuid('PagerEmployee') }}",
            "person": "{{ employee_uuid }}",
            "visibility": "{{ get_visibility_uuid('Public') }}",
        },
    },
    "username_generator": {
        "combinations_to_try": ["FFFX", "LLLX"],
    },
}


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LDAP_IT_SYSTEM": "ADUUID",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "CONVERSION_MAPPING": json.dumps(conversion_mapping_with_aduuid_itsystem),
    }
)
async def test_valid_address(
    graphql_client: GraphQLClient,
    test_client: AsyncClient,
    email_employee: UUID,
    ldap_person_uuid: UUID,
    mo_person: UUID,
    aduuid: UUID,
    add_engagement: AddEngagement,
) -> None:
    viborg_address_type_user_keys = [
        "EmailEmployee",
        "MitIDEmployee",
        "PhoneEmployee",
        "MobileEmployee",
    ]

    itsystem_uuid = aduuid
    from_date = str(datetime(1980, 1, 1))

    # Create an ITUser in MO with an ADUUID of an existing LDAP user and a known UUID
    ituser_uuid = (
        await graphql_client.ituser_create(
            ITUserCreateInput(
                person=mo_person,
                user_key=str(ldap_person_uuid),  # str(ldap_person_uuid),
                itsystem=itsystem_uuid,
                validity=RAValidityInput(from_="1970-01-01T00:00:00", to=None),
            )
        )
    ).uuid

    engagement_uuid = await add_engagement("hej")

    # Create an address for the ITUser
    # non_orphaned_address_uuid = uuid4()
    non_orphaned_address_value = "i@exist.dk"
    non_orphaned_address_uuid = (
        await graphql_client.address_create(
            AddressCreateInput(
                user_key="Should Exist",
                person=mo_person,
                ituser=ituser_uuid,
                engagement=engagement_uuid,
                address_type=email_employee,
                value=non_orphaned_address_value,
                validity=RAValidityInput(from_=from_date, to=None),
            )
        )
    ).uuid

    # Create an orphaned Address
    # address that is not associated with any ITUser or engagement
    orphaned_address_uuid = (
        await graphql_client.address_create(
            AddressCreateInput(
                person=mo_person,
                address_type=email_employee,
                value="delete_me@viborg.dk",
                validity=RAValidityInput(from_="1970-01-01T00:00:00", to=None),
            )
        )
    ).uuid

    # Dry-run: expect to see the orphaned address UUID
    response = await test_client.post(
        "/fixup/cleanup_orphaned_addresses",
        params={
            "dry_run": True,
            "address_type_user_keys": viborg_address_type_user_keys,
        },
    )
    assert response.status_code == 200
    assert str(orphaned_address_uuid) in response.json()
    assert str(orphaned_address_uuid) in response.json()
    assert len(response.json()) == 1
    assert str(non_orphaned_address_uuid) not in response.json()

    # # Call the fixup endpoint with dry_run=False, and expect to see all the ituser_uuids
    response = await test_client.post(
        "/fixup/cleanup_orphaned_addresses",
        params={
            "dry_run": False,
            "address_type_user_keys": viborg_address_type_user_keys,
        },
    )
    assert response.status_code == 200
    assert str(orphaned_address_uuid) in response.json()
    assert len(response.json()) == 1
    assert str(non_orphaned_address_uuid) not in response.json()

    # # Retest with dry-run, expecting all orphaned addresses to be gone
    response = await test_client.post(
        "/fixup/cleanup_orphaned_addresses",
        params={
            "dry_run": True,
            "address_type_user_keys": viborg_address_type_user_keys,
        },
    )
    assert response.status_code == 200
    assert response.json() == []
