# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime
from uuid import UUID
from uuid import uuid4

import pytest
from httpx import AsyncClient
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import AddressCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import AddressFilter
from mo_ldap_import_export.autogenerated_graphql_client import AddressUpdateInput
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.autogenerated_graphql_client._testing__address_read import (
    TestingAddressReadAddressesObjectsValidities as ReadValidity,
)
from mo_ldap_import_export.utils import MO_TZ

# Each validity entry is (from_, to, value).
Validity = tuple[datetime, datetime | None, str]


async def _get_validities(
    graphql_client: GraphQLClient, address_uuid: UUID
) -> list[ReadValidity]:
    addresses = await graphql_client._testing__address_read(
        filter=AddressFilter(uuids=[address_uuid], from_date=None, to_date=None),
    )
    address = one(addresses.objects)
    return address.validities


async def _create_address(
    graphql_client: GraphQLClient,
    person: UUID,
    address_type: UUID,
    validities: list[Validity],
) -> UUID:
    head, *tail = validities
    head_from, head_to, head_value = head
    address = await graphql_client.address_create(
        input=AddressCreateInput(
            user_key="test",
            person=person,
            address_type=address_type,
            value=head_value,
            validity=RAValidityInput(from_=head_from, to=head_to),
        )
    )
    for from_, to, value in tail:
        await graphql_client.address_update(
            input=AddressUpdateInput(
                uuid=address.uuid,
                user_key="test",
                value=value,
                address_type=address_type,
                person=person,
                validity=RAValidityInput(from_=from_, to=to),
            )
        )
    return address.uuid


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
    }
)
@pytest.mark.usefixtures("test_client")
@pytest.mark.parametrize(
    "validities,expected",
    [
        # Multiple past validities (with a gap) collapse to a single validity.
        (
            [
                (
                    datetime(2020, 1, 1, tzinfo=MO_TZ),
                    datetime(2021, 1, 1, tzinfo=MO_TZ),
                    "old@example.org",
                ),
                (
                    datetime(2022, 1, 1, tzinfo=MO_TZ),
                    datetime(2023, 1, 1, tzinfo=MO_TZ),
                    "mid@example.org",
                ),
                (
                    datetime(2024, 1, 1, tzinfo=MO_TZ),
                    datetime(2024, 6, 1, tzinfo=MO_TZ),
                    "new@example.org",
                ),
            ],
            (
                datetime(2020, 1, 1, tzinfo=MO_TZ),
                datetime(2024, 6, 1, tzinfo=MO_TZ),
                "new@example.org",
            ),
        ),
        # Past + currently active (to=None) preserves the open end.
        (
            [
                (
                    datetime(2020, 1, 1, tzinfo=MO_TZ),
                    datetime(2021, 1, 1, tzinfo=MO_TZ),
                    "old@example.org",
                ),
                (
                    datetime(2025, 1, 1, tzinfo=MO_TZ),
                    None,
                    "current@example.org",
                ),
            ],
            (
                datetime(2020, 1, 1, tzinfo=MO_TZ),
                None,
                "current@example.org",
            ),
        ),
        # Single past validity is left untouched.
        (
            [
                (
                    datetime(2020, 1, 1, tzinfo=MO_TZ),
                    datetime(2021, 1, 1, tzinfo=MO_TZ),
                    "lonely@example.org",
                ),
            ],
            (
                datetime(2020, 1, 1, tzinfo=MO_TZ),
                datetime(2021, 1, 1, tzinfo=MO_TZ),
                "lonely@example.org",
            ),
        ),
    ],
)
async def test_purge_collapses_validities(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
    email_employee: UUID,
    validities: list[Validity],
    expected: Validity,
) -> None:
    address_uuid = await _create_address(
        graphql_client, mo_person, email_employee, validities
    )

    response = await test_client.post(
        f"/danger/purge_address_validities/{address_uuid}"
    )
    assert response.status_code == 200, response.text
    assert response.json() == str(address_uuid)

    validity = one(await _get_validities(graphql_client, address_uuid))
    actual: Validity = (validity.validity.from_, validity.validity.to, validity.value)
    assert actual == expected


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
    }
)
@pytest.mark.usefixtures("test_client")
@pytest.mark.parametrize(
    "validities",
    [
        # Future only.
        [
            (
                datetime(2099, 1, 1, tzinfo=MO_TZ),
                datetime(2100, 1, 1, tzinfo=MO_TZ),
                "future@example.org",
            ),
        ],
        # Past + future.
        [
            (
                datetime(2020, 1, 1, tzinfo=MO_TZ),
                datetime(2021, 1, 1, tzinfo=MO_TZ),
                "old@example.org",
            ),
            (
                datetime(2099, 1, 1, tzinfo=MO_TZ),
                datetime(2100, 1, 1, tzinfo=MO_TZ),
                "future@example.org",
            ),
        ],
        # Current + future.
        [
            (
                datetime(2025, 1, 1, tzinfo=MO_TZ),
                datetime(2027, 1, 1, tzinfo=MO_TZ),
                "current@example.org",
            ),
            (
                datetime(2099, 1, 1, tzinfo=MO_TZ),
                datetime(2100, 1, 1, tzinfo=MO_TZ),
                "future@example.org",
            ),
        ],
        # Past + current + future.
        [
            (
                datetime(2020, 1, 1, tzinfo=MO_TZ),
                datetime(2021, 1, 1, tzinfo=MO_TZ),
                "old@example.org",
            ),
            (
                datetime(2025, 1, 1, tzinfo=MO_TZ),
                datetime(2027, 1, 1, tzinfo=MO_TZ),
                "current@example.org",
            ),
            (
                datetime(2099, 1, 1, tzinfo=MO_TZ),
                datetime(2100, 1, 1, tzinfo=MO_TZ),
                "future@example.org",
            ),
        ],
    ],
)
async def test_purge_refuses_future_validities(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
    email_employee: UUID,
    validities: list[Validity],
) -> None:
    address_uuid = await _create_address(
        graphql_client, mo_person, email_employee, validities
    )
    validities_before = await _get_validities(graphql_client, address_uuid)

    response = await test_client.post(
        f"/danger/purge_address_validities/{address_uuid}"
    )
    assert response.status_code == 500

    # Confirm the address has not been mutated.
    assert await _get_validities(graphql_client, address_uuid) == validities_before


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
    }
)
@pytest.mark.usefixtures("test_client")
async def test_purge_unknown_address_returns_404(
    test_client: AsyncClient,
) -> None:
    response = await test_client.post(f"/danger/purge_address_validities/{uuid4()}")
    assert response.status_code == 500
