# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import json
from uuid import UUID

import pytest
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    EmployeeCreateInput,
)
from mo_ldap_import_export.ldapapi import LDAPAPI


def read_jsonl_file(filename: str) -> list[dict]:
    with open(filename) as fin:
        file_data = []
        for line in fin.readlines():
            file_data.append(json.loads(line))
        return file_data


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "mo_to_ldap": [
                    {
                        "identifier": "inspect_test_handler",
                        "routing_key": "person",
                        "object_class": "inetOrgPerson",
                        "template": """
                        {% set mo_employee = load_mo_employee(uuid, current_objects_only=False) %}
                        {% set existing_dn = get_person_dn(uuid) %}
                        {{
                            {
                                "dn": existing_dn or ("cn=" ~ mo_employee.given_name ~ " " ~ mo_employee.surname ~ ",ou=os2mo,o=magenta,dc=magenta,dc=dk"),
                                "create": existing_dn is none,
                                "attributes": {
                                    "employeeNumber": mo_employee.cpr_number,
                                    "givenName": mo_employee.given_name,
                                    "sn": mo_employee.surname,
                                    "title": uuid|string
                                }
                            }|tojson
                        }}
                        """,
                    }
                ]
            }
        ),
    }
)
async def test_inspect_mo_to_ldap_template_all(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    write_ldap_api: LDAPAPI,
    ldap_org_unit: list[str],
) -> None:
    # 1. Created (exists in MO, not in LDAP)
    r1 = await graphql_client.person_create(
        input=EmployeeCreateInput(
            given_name="Create",
            surname="Me",
            cpr_number="1101010001",
        )
    )
    uuid_create = r1.uuid
    dn_create = "cn=Create Me,ou=os2mo,o=magenta,dc=magenta,dc=dk"

    # 2. Edited (exists in MO, exists in LDAP with different attribute)
    r2 = await graphql_client.person_create(
        input=EmployeeCreateInput(
            given_name="Edit",
            surname="Me",
            cpr_number="1201010002",
        )
    )
    uuid_edit = r2.uuid
    dn_edit = "cn=Edit Me,ou=os2mo,o=magenta,dc=magenta,dc=dk"
    await write_ldap_api.ldap_connection.ldap_add(
        dn_edit,
        object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
        attributes={
            "cn": "Edit Me",
            "givenName": "Edit",
            "sn": "Me",
            "employeeNumber": "1201010002",
            "title": "Old Title",
        },
    )

    # 3. Nothing happens (exists in MO, exists in LDAP with same attributes)
    r3 = await graphql_client.person_create(
        input=EmployeeCreateInput(
            given_name="Nothing",
            surname="Happens",
            cpr_number="1301010003",
        )
    )
    uuid_nothing = r3.uuid
    dn_nothing = "cn=Nothing Happens,ou=os2mo,o=magenta,dc=magenta,dc=dk"
    await write_ldap_api.ldap_connection.ldap_add(
        dn_nothing,
        object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
        attributes={
            "cn": "Nothing Happens",
            "givenName": "Nothing",
            "sn": "Happens",
            "employeeNumber": "1301010003",
            "title": str(uuid_nothing),
        },
    )

    response = await test_client.get("/Inspect/mo_to_ldap/all")
    assert response.status_code == 200
    result = response.json()
    assert result == "OK"

    file_data = read_jsonl_file("/tmp/mo_to_ldap.jsonl")

    # Helper to find output for a uuid
    def find_by_uuid(uuid: UUID):
        return [row for row in file_data if row.get("__mo_uuid") == str(uuid)]

    # Verify Created
    out_create = find_by_uuid(uuid_create)
    assert len(out_create) == 1
    assert out_create[0] == {
        "__mo_uuid": str(uuid_create),
        "identifier": "inspect_test_handler",
        "dn": dn_create,
        "message": "Would have created",
        "object_class": "inetOrgPerson",
        "attributes": {
            "employeeNumber": ["1101010001"],
            "givenName": ["Create"],
            "sn": ["Me"],
            "title": [str(uuid_create)],
        },
    }

    # Verify Edited
    out_edit = find_by_uuid(uuid_edit)
    assert len(out_edit) == 1
    assert out_edit[0] == {
        "__mo_uuid": str(uuid_edit),
        "identifier": "inspect_test_handler",
        "dn": dn_edit,
        "message": "Would have changed attributes",
        "attributes": {"title": [str(uuid_edit)]},
        "old_attributes": {"title": ["Old Title"]},
    }

    # Verify Nothing happens
    out_nothing = find_by_uuid(uuid_nothing)
    assert len(out_nothing) == 1
    assert out_nothing[0] == {
        "__mo_uuid": str(uuid_nothing),
        "identifier": "inspect_test_handler",
        "message": "No changes",
    }
