# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from uuid import UUID
from uuid import uuid4

import pytest
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    AddressCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ClassCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITUserCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RAValidityInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RoleBindingCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import ValidityInput


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LDAP_IT_SYSTEM": "",
    }
)
@pytest.mark.parametrize("num_itusers", (0, 1, 5))
async def test_delete_all_itusers_for_itsystems(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
    aduuid: UUID,
    num_itusers: int,
) -> None:
    # Populate the (deprecated) IT-system with a number of IT-users
    ituser_uuids = set()
    for _ in range(num_itusers):
        ituser = await graphql_client.ituser_create(
            ITUserCreateInput(
                person=mo_person,
                user_key=str(uuid4()),
                itsystem=aduuid,
                validity=RAValidityInput(from_="1970-01-01T00:00:00"),
            )
        )
        ituser_uuids.add(str(ituser.uuid))

    # Dry-run: expect to see all the IT-user UUIDs that would be deleted
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"itsystem_user_key": "ADUUID"},
    )
    assert response.status_code == 200
    assert set(response.json()) == ituser_uuids

    # dry_run=False: actually delete them, expecting all the IT-user UUIDs back
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"itsystem_user_key": "ADUUID", "dry_run": "false"},
    )
    assert response.status_code == 200
    assert set(response.json()) == ituser_uuids

    # The IT-system itself is now gone too, so a follow-up call 404s
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"itsystem_user_key": "ADUUID"},
    )
    assert response.status_code == 404


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LDAP_IT_SYSTEM": "",
    }
)
async def test_delete_all_itusers_for_itsystems_unknown_itsystem(
    test_client: AsyncClient,
) -> None:
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"itsystem_user_key": "Does-Not-Exist"},
    )
    assert response.status_code == 404


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LDAP_IT_SYSTEM": "",
    }
)
async def test_delete_all_itusers_for_itsystems_aborts_on_dangling(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
    email_employee: UUID,
    public: UUID,
    aduuid: UUID,
) -> None:
    # Create an IT-user in the (deprecated) IT-system with an address scoped to it
    ituser = await graphql_client.ituser_create(
        ITUserCreateInput(
            person=mo_person,
            user_key=str(uuid4()),
            itsystem=aduuid,
            validity=RAValidityInput(from_="1970-01-01T00:00:00"),
        )
    )
    address = await graphql_client.address_create(
        input=AddressCreateInput(
            value="test@example.com",
            address_type=email_employee,
            visibility=public,
            person=mo_person,
            ituser=ituser.uuid,
            validity=RAValidityInput(from_="1970-01-01T00:00:00"),
        )
    )
    address_uuid = address.uuid

    # A dry-run reports the dangling address via a 409
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"itsystem_user_key": "ADUUID"},
    )
    assert response.status_code == 409
    detail = response.json()["detail"]
    assert detail["dangling_references"]["addresses"] == [str(address_uuid)]

    # An actual deletion is likewise refused due to the dangling address
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"itsystem_user_key": "ADUUID", "dry_run": "false"},
    )
    assert response.status_code == 409
    detail = response.json()["detail"]
    assert detail["dangling_references"]["addresses"] == [str(address_uuid)]


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LDAP_IT_SYSTEM": "",
    }
)
async def test_delete_all_itusers_for_itsystems_aborts_on_dangling_rolebinding(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
    role_facet: UUID,
    aduuid: UUID,
) -> None:
    # Create an IT-user in the (deprecated) IT-system with a rolebinding scoped to it
    ituser = await graphql_client.ituser_create(
        ITUserCreateInput(
            person=mo_person,
            user_key=str(uuid4()),
            itsystem=aduuid,
            validity=RAValidityInput(from_="1970-01-01T00:00:00"),
        )
    )
    role = await graphql_client.class_create(
        input=ClassCreateInput(
            name="admin",
            user_key="admin",
            scope="TEXT",
            facet_uuid=role_facet,
            it_system_uuid=aduuid,
            validity=ValidityInput(from_="1970-01-01T00:00:00Z"),
        )
    )
    rolebinding = await graphql_client._testing__rolebinding_create(
        input=RoleBindingCreateInput(
            user_key="-",
            ituser=ituser.uuid,
            role=role.uuid,
            validity=RAValidityInput(from_="1970-01-01T00:00:00"),
        )
    )

    # A dry-run reports the dangling rolebinding via a 409
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"itsystem_user_key": "ADUUID"},
    )
    assert response.status_code == 409
    detail = response.json()["detail"]
    assert detail["dangling_references"]["rolebindings"] == [str(rolebinding.uuid)]

    # An actual deletion is likewise refused due to the dangling rolebinding
    response = await test_client.post(
        "/fixup/delete_all_itusers_for_itsystems",
        params={"itsystem_user_key": "ADUUID", "dry_run": "false"},
    )
    assert response.status_code == 409
    detail = response.json()["detail"]
    assert detail["dangling_references"]["rolebindings"] == [str(rolebinding.uuid)]
