# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import json
from uuid import UUID

import pytest
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    EmployeeCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITUserCreateInput,
)
from mo_ldap_import_export.ldapapi import LDAPAPI


def read_jsonl_file(filename: str) -> list[dict]:
    with open(filename) as fin:
        file_data = []
        for line in fin.readlines():
            file_data.append(json.loads(line))
        return file_data


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "mo_to_ldap": [
                    {
                        "identifier": "inspect_test_handler_ituser",
                        "routing_key": "ituser",
                        "object_class": "inetOrgPerson",
                        "template": """
                        {% set mo_ituser = load_mo_it_user({"uuids": [uuid]}) %}
                        {% set mo_employee = load_mo_employee(mo_ituser.person) %}
                        {% set existing_dn = get_person_dn(mo_employee.uuid) %}
                        {{
                            {
                                "dn": existing_dn or ("cn=" ~ mo_employee.given_name ~ " " ~ mo_employee.surname ~ ",ou=os2mo,o=magenta,dc=magenta,dc=dk"),
                                "create": existing_dn is none,
                                "attributes": {
                                    "uid": mo_ituser.user_key,
                                    "employeeNumber": mo_employee.cpr_number,
                                    "givenName": mo_employee.given_name,
                                    "sn": mo_employee.surname,
                                    "title": mo_ituser.uuid|string
                                }
                            }|tojson
                        }}
                        """,
                    }
                ]
            }
        ),
    }
)
async def test_inspect_mo_to_ldap_ituser_template_all(
    adtitle: UUID,
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    write_ldap_api: LDAPAPI,
    ldap_org_unit: list[str],
) -> None:
    # 1. Setup Active Directory IT System

    # 2. Created IT User
    r1 = await graphql_client.person_create(
        input=EmployeeCreateInput(
            given_name="CreateIT",
            surname="Me",
            cpr_number="1101010004",
        )
    )
    it1 = await graphql_client.ituser_create(
        input=ITUserCreateInput(
            person=r1.uuid,
            itsystem=adtitle,
            user_key="create_it_user",
            validity={"from": "2020-01-01T00:00:00"},
        )
    )
    uuid_create = it1.uuid
    dn_create = "cn=CreateIT Me,ou=os2mo,o=magenta,dc=magenta,dc=dk"

    # 3. Edited IT User
    r2 = await graphql_client.person_create(
        input=EmployeeCreateInput(
            given_name="EditIT",
            surname="Me",
            cpr_number="1201010005",
        )
    )
    it2 = await graphql_client.ituser_create(
        input=ITUserCreateInput(
            person=r2.uuid,
            itsystem=adtitle,
            user_key="edit_it_user",
            validity={"from": "2020-01-01T00:00:00"},
        )
    )
    uuid_edit = it2.uuid
    dn_edit = "cn=EditIT Me,ou=os2mo,o=magenta,dc=magenta,dc=dk"
    await write_ldap_api.ldap_connection.ldap_add(
        dn_edit,
        object_class=["top", "person", "organizationalPerson", "inetOrgPerson"],
        attributes={
            "cn": "EditIT Me",
            "givenName": "EditIT",
            "sn": "Me",
            "employeeNumber": "1201010005",
            "uid": "edit_it_user",
            "title": "Old IT Title",
        },
    )

    response = await test_client.get("/Inspect/mo_to_ldap/ituser/all")
    assert response.status_code == 200
    result = response.json()
    assert result == "OK"

    file_data = read_jsonl_file("/tmp/mo_to_ldap_ituser.jsonl")

    def find_by_uuid(uuid: UUID):
        return [row for row in file_data if row.get("__mo_uuid") == str(uuid)]

    # Verify Created
    out_create = find_by_uuid(uuid_create)
    assert len(out_create) == 1
    assert out_create[0] == {
        "__mo_uuid": str(uuid_create),
        "__mo_employee_uuid": str(r1.uuid),
        "identifier": "inspect_test_handler_ituser",
        "dn": dn_create,
        "message": "Would have created",
        "object_class": "inetOrgPerson",
        "attributes": {
            "uid": ["create_it_user"],
            "employeeNumber": ["1101010004"],
            "givenName": ["CreateIT"],
            "sn": ["Me"],
            "title": [str(uuid_create)],
        },
    }

    # Verify Edited
    out_edit = find_by_uuid(uuid_edit)
    assert len(out_edit) == 1
    assert out_edit[0] == {
        "__mo_uuid": str(uuid_edit),
        "__mo_employee_uuid": str(r2.uuid),
        "identifier": "inspect_test_handler_ituser",
        "dn": dn_edit,
        "message": "Would have changed attributes",
        "attributes": {"title": [str(uuid_edit)]},
        "old_attributes": {"title": ["Old IT Title"]},
    }
