# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from uuid import UUID

import pytest
from httpx import AsyncClient
from more_itertools import last
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import AddressCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import AddressFilter
from mo_ldap_import_export.autogenerated_graphql_client import EngagementCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import EngagementFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import ITUserCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import ITUserTerminateInput
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITSystemCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RAOpenValidityInput,
)
from mo_ldap_import_export.utils import MO_TZ

ENDPOINT = "/fixup/terminate_dangling_it_user_relations"
EPOCH = datetime(1980, 1, 1, tzinfo=MO_TZ)
ITUSER_TERMINATION = datetime(2020, 6, 15, tzinfo=MO_TZ)


@pytest.fixture
async def aduuid_itsystem(
    read_itsystem_by_user_key: Callable[[str], Awaitable[UUID]],
    aduuid: UUID,
) -> UUID:
    return await read_itsystem_by_user_key("ADUUID")


async def _engagement_to(graphql_client: GraphQLClient, uuid: UUID) -> datetime | None:
    result = await graphql_client.read_engagements(
        EngagementFilter(uuids=[uuid], from_date=None, to_date=None)
    )
    return last(one(result.objects).validities).validity.to


async def _address_to(graphql_client: GraphQLClient, uuid: UUID) -> datetime | None:
    result = await graphql_client._testing__address_read(
        filter=AddressFilter(uuids=[uuid], from_date=None, to_date=None)
    )
    return last(one(result.objects).validities).validity.to


async def _create_engagement(
    graphql_client: GraphQLClient,
    user_key: str,
    person: UUID,
    org_unit: UUID,
    ansat: UUID,
    jurist: UUID,
    primary: UUID,
    to: datetime | None = None,
) -> UUID:
    result = await graphql_client.engagement_create(
        input=EngagementCreateInput(
            user_key=user_key,
            person=person,
            org_unit=org_unit,
            engagement_type=ansat,
            job_function=jurist,
            primary=primary,
            validity=RAValidityInput(from_=EPOCH, to=to),
        )
    )
    return result.uuid


async def _create_ituser(
    graphql_client: GraphQLClient,
    user_key: str,
    itsystem: UUID,
    person: UUID,
    engagement: UUID | None = None,
) -> UUID:
    result = await graphql_client.ituser_create(
        input=ITUserCreateInput(
            user_key=user_key,
            itsystem=itsystem,
            person=person,
            engagement=engagement,
            validity=RAValidityInput(from_=EPOCH),
        )
    )
    return result.uuid


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
    }
)
async def test_missing_it_system_parameter(test_client: AsyncClient) -> None:
    """`it_system` is required; omitting it must yield a validation error."""
    response = await test_client.post(ENDPOINT)
    assert response.status_code == 422
    assert response.json() == {
        "detail": [
            {
                "loc": ["query", "it_system"],
                "msg": "field required",
                "type": "value_error.missing",
            }
        ]
    }


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
    }
)
async def test_nothing_to_fix(
    test_client: AsyncClient,
    aduuid_itsystem: UUID,
) -> None:
    """No IT-users at all → empty response."""
    response = await test_client.post(
        ENDPOINT, params={"it_system": str(aduuid_itsystem)}
    )
    assert response.status_code == 200
    assert response.json() == {}


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
    }
)
@pytest.mark.parametrize(
    "engagement_to,ituser_to",
    [
        # Active IT-user (no termination): engagement is not dangling.
        pytest.param(None, None, id="active_ituser"),
        # IT-user terminated, but engagement already ends earlier: not dangling.
        pytest.param(
            datetime(2019, 1, 1, tzinfo=MO_TZ),
            ITUSER_TERMINATION,
            id="engagement_ends_before_ituser",
        ),
    ],
)
async def test_no_dangling_relations(
    engagement_to: datetime | None,
    ituser_to: datetime | None,
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    aduuid_itsystem: UUID,
    mo_person: UUID,
    mo_org_unit: UUID,
    ansat: UUID,
    jurist: UUID,
    primary: UUID,
) -> None:
    """The endpoint returns nothing when no engagement outlives its IT-user."""
    engagement_uuid = await _create_engagement(
        graphql_client,
        "eng",
        mo_person,
        mo_org_unit,
        ansat,
        jurist,
        primary,
        to=engagement_to,
    )
    ituser_uuid = await _create_ituser(
        graphql_client,
        "ituser",
        aduuid_itsystem,
        mo_person,
        engagement=engagement_uuid,
    )
    if ituser_to is not None:
        await graphql_client.ituser_terminate(
            input=ITUserTerminateInput(uuid=ituser_uuid, to=ituser_to)
        )

    response = await test_client.post(
        ENDPOINT, params={"it_system": str(aduuid_itsystem)}
    )
    assert response.status_code == 200
    assert response.json() == {}
    assert await _engagement_to(graphql_client, engagement_uuid) == engagement_to


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
    }
)
@pytest.mark.parametrize(
    "engagement_to",
    [
        pytest.param(None, id="open_ended_engagement"),
        pytest.param(
            datetime(2025, 1, 1, tzinfo=MO_TZ), id="engagement_ends_after_ituser"
        ),
    ],
)
async def test_terminate_dangling_engagement_and_address(
    engagement_to: datetime | None,
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    aduuid_itsystem: UUID,
    mo_person: UUID,
    mo_org_unit: UUID,
    ansat: UUID,
    jurist: UUID,
    primary: UUID,
    email_employee: UUID,
) -> None:
    """A terminated IT-user with a dangling engagement and dangling address
    should have both terminated at the IT-user's termination date.

    Unrelated engagements and addresses must remain untouched.
    """
    dangling_engagement = await _create_engagement(
        graphql_client,
        "dangling-eng",
        mo_person,
        mo_org_unit,
        ansat,
        jurist,
        primary,
        to=engagement_to,
    )
    untouched_engagement = await _create_engagement(
        graphql_client,
        "untouched-eng",
        mo_person,
        mo_org_unit,
        ansat,
        jurist,
        primary,
    )

    ituser_uuid = await _create_ituser(
        graphql_client,
        "terminated-ituser",
        aduuid_itsystem,
        mo_person,
        engagement=dangling_engagement,
    )

    dangling_address = await graphql_client.address_create(
        input=AddressCreateInput(
            user_key="dangling-addr",
            person=mo_person,
            address_type=email_employee,
            value="dangling@example.com",
            ituser=ituser_uuid,
            validity=RAValidityInput(from_=EPOCH),
        )
    )
    # An address without an ituser link must not be touched.
    untouched_address = await graphql_client.address_create(
        input=AddressCreateInput(
            user_key="untouched-addr",
            person=mo_person,
            address_type=email_employee,
            value="untouched@example.com",
            validity=RAValidityInput(from_=EPOCH),
        )
    )

    await graphql_client.ituser_terminate(
        input=ITUserTerminateInput(uuid=ituser_uuid, to=ITUSER_TERMINATION)
    )

    # Dry-run reports the dangling relations.
    dry_response = await test_client.post(
        ENDPOINT, params={"it_system": str(aduuid_itsystem)}
    )
    assert dry_response.status_code == 200
    body = dry_response.json()
    assert set(body.keys()) == {str(ituser_uuid)}
    entry = body[str(ituser_uuid)]
    assert entry["engagements"] == [str(dangling_engagement)]
    assert entry["addresses"] == [str(dangling_address.uuid)]
    assert entry["termination_date"].startswith("2020-06-15")

    # Dry-run must not mutate state.
    assert await _engagement_to(graphql_client, dangling_engagement) == engagement_to
    assert await _address_to(graphql_client, dangling_address.uuid) is None

    # Real run terminates the dangling relations.
    run_response = await test_client.post(
        ENDPOINT,
        params={"it_system": str(aduuid_itsystem), "dry_run": False},
    )
    assert run_response.status_code == 200
    assert run_response.json() == body

    assert (
        await _engagement_to(graphql_client, dangling_engagement) == ITUSER_TERMINATION
    )
    assert (
        await _address_to(graphql_client, dangling_address.uuid) == ITUSER_TERMINATION
    )
    # The unrelated engagement and address are unchanged.
    assert await _engagement_to(graphql_client, untouched_engagement) is None
    assert await _address_to(graphql_client, untouched_address.uuid) is None

    # A subsequent dry-run finds nothing left.
    after = await test_client.post(ENDPOINT, params={"it_system": str(aduuid_itsystem)})
    assert after.status_code == 200
    assert after.json() == {}


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
    }
)
async def test_it_system_parameter_scopes_the_search(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    aduuid_itsystem: UUID,
    mo_person: UUID,
    mo_org_unit: UUID,
    ansat: UUID,
    jurist: UUID,
    primary: UUID,
) -> None:
    """The endpoint only considers IT-users in the supplied IT-system.

    A terminated IT-user under one IT-system must not be reported when the
    other IT-system is queried, and vice versa.
    """
    other_itsystem = (
        await graphql_client.itsystem_create(
            input=ITSystemCreateInput(
                user_key="Other",
                name="Other IT-system",
                validity=RAOpenValidityInput(from_="1970-01-01T00:00:00Z"),
            )
        )
    ).uuid

    engagement_uuid = await _create_engagement(
        graphql_client,
        "other-eng",
        mo_person,
        mo_org_unit,
        ansat,
        jurist,
        primary,
    )
    ituser_uuid = await _create_ituser(
        graphql_client,
        "other-ituser",
        other_itsystem,
        mo_person,
        engagement=engagement_uuid,
    )
    await graphql_client.ituser_terminate(
        input=ITUserTerminateInput(uuid=ituser_uuid, to=ITUSER_TERMINATION)
    )

    # Querying the LDAP IT-system: invisible.
    aduuid_response = await test_client.post(
        ENDPOINT, params={"it_system": str(aduuid_itsystem)}
    )
    assert aduuid_response.status_code == 200
    assert aduuid_response.json() == {}

    # Querying the actual owning IT-system: picked up.
    other_response = await test_client.post(
        ENDPOINT, params={"it_system": str(other_itsystem)}
    )
    assert other_response.status_code == 200
    body = other_response.json()
    assert set(body.keys()) == {str(ituser_uuid)}
    assert body[str(ituser_uuid)]["engagements"] == [str(engagement_uuid)]

    # Terminate, then verify it actually ran.
    run_response = await test_client.post(
        ENDPOINT,
        params={"it_system": str(other_itsystem), "dry_run": False},
    )
    assert run_response.status_code == 200
    assert run_response.json() == body
    assert await _engagement_to(graphql_client, engagement_uuid) == ITUSER_TERMINATION
