# SPDX-FileCopyrightText: Viborg kommune <https://viborg.dk/>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import Awaitable
from collections.abc import Callable
from uuid import UUID
from uuid import uuid4

import pytest
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITUserCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RAValidityInput,
)
from mo_ldap_import_export.types import LDAPUUID

conversion_mapping_with_aduuid_itsystem = {
    "ldap_to_mo": {
        "Employee": {
            "objectClass": "Employee",
            "_import_to_mo_": "false",
            "_ldap_attributes_": [],
            "uuid": "{{ employee_uuid or '' }}",
        },
        "ADUUID": {
            "objectClass": "ITUser",
            "_import_to_mo_": "true",
            "_ldap_attributes_": ["entryUUID"],
            "uuid": "{{ get_ituser_uuid({'itsystem': {'user_keys': ['ADUUID']}, 'employee': {'uuids': [employee_uuid]}}) }}",
            "user_key": "{{ ldap.entryUUID }}",
            "itsystem": "{{ get_it_system_uuid('ADUUID') }}",
            "person": "{{ employee_uuid or '' }}",
        },
        "EmailEmployee": {
            "objectClass": "Address",
            "_import_to_mo_": "true",
            "_ldap_attributes_": ["carLicense", "mail"],
            # carLicense is arbitrarily chosen as an enabled/disabled marker
            "_terminate_": "{{ now()|mo_datestring if ldap.carLicense == 'EXPIRED' else '' }}",
            "uuid": "{{ get_address_uuid({'address_type': {'user_keys': ['EmailEmployee']}, 'employee': {'uuids': [employee_uuid]}}) }}",
            "value": "{{ ldap.mail }}",
            "address_type": "{{ get_employee_address_type_uuid('EmailEmployee') }}",
            "person": "{{ employee_uuid }}",
            "visibility": "{{ get_visibility_uuid('Public') }}",
        },
        "MitIDEmployee": {
            "objectClass": "Address",
            "_import_to_mo_": "true",
            "_ldap_attributes_": ["carLicense", "mail"],
            # carLicense is arbitrarily chosen as an enabled/disabled marker
            "_terminate_": "{{ now()|mo_datestring if ldap.carLicense == 'EXPIRED' else '' }}",
            "uuid": "{{ get_address_uuid({'address_type': {'user_keys': ['PhoneEmployee']}, 'employee': {'uuids': [employee_uuid]}}) }}",
            "value": "{{ ldap.mobile }}",
            "address_type": "{{ get_employee_address_type_uuid('PhoneEmployee') }}",
            "person": "{{ employee_uuid }}",
            "visibility": "{{ get_visibility_uuid('Public') }}",
        },
        "PhoneEmployee": {
            "objectClass": "Address",
            "_import_to_mo_": "true",
            "_ldap_attributes_": ["carLicense", "mail"],
            # carLicense is arbitrarily chosen as an enabled/disabled marker
            "_terminate_": "{{ now()|mo_datestring if ldap.carLicense == 'EXPIRED' else '' }}",
            "uuid": "{{ get_address_uuid({'address_type': {'user_keys': ['MitIDEmployee']}, 'employee': {'uuids': [employee_uuid]}}) }}",
            "value": "{{ ldap.altSecurityIdentities }}",
            "address_type": "{{ get_employee_address_type_uuid('MitIDEmployee') }}",
            "person": "{{ employee_uuid }}",
            "visibility": "{{ get_visibility_uuid('Public') }}",
        },
    },
    "username_generator": {
        "combinations_to_try": ["FFFX", "LLLX"],
    },
}
