# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Tests for midnight enforcement on endpoints that forward `at` to MO."""

import json
from collections.abc import Awaitable
from collections.abc import Callable
from uuid import UUID
from uuid import uuid4

import pytest
from httpx import AsyncClient

from mo_ldap_import_export.autogenerated_graphql_client import AddressCreateInput
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITSystemCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITUserCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RAOpenValidityInput,
)


@pytest.fixture
async def account_name_itsystem(graphql_client: GraphQLClient) -> UUID:
    itsystem = await graphql_client.itsystem_create(
        input=ITSystemCreateInput(
            user_key="account_name",
            name="Account Name",
            validity=RAOpenValidityInput(from_="1970-01-01T00:00:00Z"),
        )
    )
    return itsystem.uuid


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "CONVERSION_MAPPING": json.dumps(
            {"username_generator": {"existing_usernames_itsystem": "account_name"}}
        ),
    }
)
@pytest.mark.parametrize(
    "at",
    [
        "2026-06-01T00:00:00Z",  # aware: midnight UTC == 02:00 Copenhagen
        "2026-06-01T02:00:00",  # naive: assumed Copenhagen, not midnight
    ],
)
@pytest.mark.usefixtures("ldap_person")
async def test_account_names_at_not_midnight(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    account_name_itsystem: UUID,
    mo_person: UUID,
    at: str,
) -> None:
    await graphql_client.ituser_create(
        ITUserCreateInput(
            user_key="cba",
            itsystem=account_name_itsystem,
            person=mo_person,
            validity=RAValidityInput(from_="1980-01-01T00:00:00"),
        )
    )

    response = await test_client.post(
        "/fixup/delete_non_existing_account_names",
        params={"at": at, "dry_run": "False"},
    )
    assert response.status_code == 500
    assert "AssertionError: 'at' is not at midnight" in response.text


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LDAP_IT_SYSTEM": "ADUUID",
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo_any": {
                    "ADUUID": [
                        {
                            "objectClass": "ITUser",
                            "_import_to_mo_": "true",
                            "_ldap_attributes_": ["entryUUID"],
                            "uuid": "{{ get_ituser_uuid({'itsystem': {'user_keys': ['ADUUID']}, 'employee': {'uuids': [employee_uuid]}}) }}",
                            "user_key": "{{ ldap.entryUUID }}",
                            "itsystem": "{{ get_it_system_uuid('ADUUID') }}",
                            "person": "{{ employee_uuid or '' }}",
                        }
                    ],
                },
            }
        ),
    }
)
@pytest.mark.parametrize(
    "at",
    [
        "2026-06-01T00:00:00Z",  # aware: midnight UTC == 02:00 Copenhagen
        "2026-06-01T02:00:00",  # naive: assumed Copenhagen, not midnight
    ],
)
@pytest.mark.usefixtures("ldap_person_uuid")
async def test_unique_ldap_uuids_at_not_midnight(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
    read_itsystem_by_user_key: Callable[[str], Awaitable[UUID]],
    at: str,
) -> None:
    aduuid_itsystem = await read_itsystem_by_user_key("ADUUID")
    await graphql_client.ituser_create(
        ITUserCreateInput(
            person=mo_person,
            user_key=str(uuid4()),
            itsystem=aduuid_itsystem,
            validity=RAValidityInput(from_="1970-01-01T00:00:00"),
        )
    )

    response = await test_client.post(
        "/fixup/delete_non_existing_unique_ldap_uuids",
        params={"at": at, "dry_run": "False"},
    )
    assert response.status_code == 500
    assert "AssertionError: 'at' is not at midnight" in response.text


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "CONVERSION_MAPPING": json.dumps(
            {"username_generator": {"existing_usernames_itsystem": "account_name"}}
        ),
    }
)
@pytest.mark.parametrize(
    "at",
    [
        "2026-06-01T00:00:00Z",  # aware: midnight UTC == 02:00 Copenhagen
        "2026-06-01T02:00:00",  # naive: assumed Copenhagen, not midnight
    ],
)
@pytest.mark.usefixtures("ldap_person")
async def test_external_ids_at_not_midnight(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    account_name_itsystem: UUID,
    mo_person: UUID,
    at: str,
) -> None:
    await graphql_client.ituser_create(
        ITUserCreateInput(
            user_key="cba",
            itsystem=account_name_itsystem,
            person=mo_person,
            external_id=str(uuid4()),
            validity=RAValidityInput(from_="1980-01-01T00:00:00"),
        )
    )

    response = await test_client.post(
        "/fixup/delete_non_existing_external_ids",
        params={"at": at, "dry_run": "False"},
    )
    assert response.status_code == 500
    assert "AssertionError: 'at' is not at midnight" in response.text


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_LDAP": "False",
        "LISTEN_TO_CHANGES_IN_MO": "False",
    }
)
@pytest.mark.parametrize(
    "at",
    [
        "2026-06-01T00:00:00Z",  # aware: midnight UTC == 02:00 Copenhagen
        "2026-06-01T02:00:00",  # naive: assumed Copenhagen, not midnight
    ],
)
@pytest.mark.usefixtures("ldap_person")
async def test_purge_addresses_at_not_midnight(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mo_person: UUID,
    email_employee: UUID,
    at: str,
) -> None:
    # Two addresses of the same type so the cleanup loop has something to terminate.
    for value in ("a@example.org", "b@example.org"):
        await graphql_client.address_create(
            input=AddressCreateInput(
                user_key="test",
                person=mo_person,
                address_type=email_employee,
                value=value,
                validity=RAValidityInput(from_="1980-01-01T00:00:00"),
            )
        )

    response = await test_client.delete(
        "/danger/purge_addresses",
        params={
            "address_type_user_key": "EmailEmployee",
            "at": at,
            "dry_run": "False",
        },
    )
    assert response.status_code == 500
    assert "AssertionError: 'at' is not at midnight" in response.text
