# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Integration tests for the disabled-account cleanup endpoint against Samba AD.

A disabled AD account is still present in LDAP (it merely has the ACCOUNTDISABLE
bit set in `userAccountControl`), so the `delete_non_existing_account_names`
cleanup does not catch IT-users pointing at it. `delete_disabled_account_names`
fills that gap.
"""

from datetime import datetime
from uuid import UUID

import pytest
from httpx import AsyncClient
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.autogenerated_graphql_client import RAValidityInput
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITSystemCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    ITUserCreateInput,
)
from mo_ldap_import_export.autogenerated_graphql_client.input_types import (
    RAOpenValidityInput,
)
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.utils import MO_TZ
from mo_ldap_import_export.utils import combine_dn_strings

# Active Directory userAccountControl flags.
UF_NORMAL_ACCOUNT = 0x0200
UF_ACCOUNTDISABLE = 0x0002


@pytest.fixture
async def account_name_itsystem(graphql_client: GraphQLClient, root_org: UUID) -> UUID:
    account_name = await graphql_client.itsystem_create(
        input=ITSystemCreateInput(
            user_key="account_name",
            name="Account Name",
            validity=RAOpenValidityInput(from_="1970-01-01T00:00:00Z"),
        )
    )
    return account_name.uuid


@pytest.mark.integration_test
@pytest.mark.usefixtures("test_client", "purge_ldap")
async def test_delete_disabled_account_names(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    ldap_api: LDAPAPI,
    ldap_org_unit: list[str],
    account_name_itsystem: UUID,
    mo_person: UUID,
) -> None:
    # Create a disabled account in AD (ACCOUNTDISABLE bit set).
    disabled_dn = combine_dn_strings(["CN=Disabled User"] + ldap_org_unit)
    await ldap_api.add_ldap_object(
        disabled_dn,
        object_class="user",
        attributes={
            "sn": ["Disabled"],
            "sAMAccountName": ["disableduser"],
            "userPrincipalName": ["disableduser@magenta.dk"],
            "userAccountControl": [str(UF_NORMAL_ACCOUNT | UF_ACCOUNTDISABLE)],
        },
    )

    # Sanity-check our setup: the account really is flagged disabled in AD, and
    # the baseline Administrator account really is enabled.
    disabled_uac = int(
        await ldap_api.get_attribute_by_dn(disabled_dn, "userAccountControl")
    )
    assert disabled_uac & UF_ACCOUNTDISABLE
    admin_dn = "CN=Administrator,CN=Users,DC=magenta,DC=dk"
    admin_uac = int(await ldap_api.get_attribute_by_dn(admin_dn, "userAccountControl"))
    assert not admin_uac & UF_ACCOUNTDISABLE

    ituser_start = datetime(1980, 1, 1, tzinfo=MO_TZ)

    async def make_ituser(user_key: str) -> UUID:
        result = await graphql_client.ituser_create(
            input=ITUserCreateInput(
                user_key=user_key,
                itsystem=account_name_itsystem,
                person=mo_person,
                validity=RAValidityInput(from_=ituser_start),
            )
        )
        return result.uuid

    # Points at the disabled account: should be collected.
    disabled_ituser = await make_ituser("disableduser")
    # Points at the enabled Administrator account: should persist.
    enabled_ituser = await make_ituser("Administrator")
    # Points at an account that does not exist at all: should NOT be collected by
    # this endpoint (that is the job of delete_non_existing_account_names).
    ghost_ituser = await make_ituser("ghostuser")

    termination_time = datetime(2025, 1, 1, tzinfo=MO_TZ)

    # Dry-run: only the disabled account's IT-user is collected.
    response = await test_client.post(
        "/fixup/delete_disabled_account_names",
        params={
            "at": termination_time.isoformat(),
            "itsystem_user_key": "account_name",
        },
    )
    assert response.status_code == 200
    assert response.json() == [str(disabled_ituser)]

    # Actually terminate it.
    response = await test_client.post(
        "/fixup/delete_disabled_account_names",
        params={
            "at": termination_time.isoformat(),
            "itsystem_user_key": "account_name",
            "dry_run": False,
        },
    )
    assert response.status_code == 200
    assert response.json() == [str(disabled_ituser)]

    # Dry-run again: nothing left to collect.
    response = await test_client.post(
        "/fixup/delete_disabled_account_names",
        params={
            "at": termination_time.isoformat(),
            "itsystem_user_key": "account_name",
        },
    )
    assert response.status_code == 200
    assert response.json() == []

    # The disabled IT-user is terminated; the others are untouched.
    result = await graphql_client.read_itusers(
        uuids=[disabled_ituser, enabled_ituser, ghost_ituser],
        from_date=None,
        to_date=None,
    )
    validities = {
        one(obj["validities"])["user_key"]: one(obj["validities"])["validity"]["to"]
        for obj in result.dict()["objects"]
    }
    assert validities == {
        "disableduser": termination_time,
        "Administrator": None,
        "ghostuser": None,
    }
