# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""End-to-end integration test: Samba AD → DirSync → MO."""

import json
from typing import Any
from unittest.mock import ANY

import pytest
from fastramqpi.pytest_util import retrying
from more_itertools import one

from mo_ldap_import_export.autogenerated_graphql_client import EmployeeFilter
from mo_ldap_import_export.autogenerated_graphql_client import GraphQLClient
from mo_ldap_import_export.ldapapi import LDAPAPI
from mo_ldap_import_export.utils import combine_dn_strings

from .conftest import SAMBA_ENVVARS


@pytest.mark.samba_test
@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        **SAMBA_ENVVARS,
        "LDAP_EVENT_GENERATOR_TYPE": "dirsync",
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "LISTEN_TO_CHANGES_IN_LDAP": "True",
        "LDAP_OBJECT_CLASS": "user",
        "LDAP_CPR_ATTRIBUTE": "employeeNumber",
        "CONVERSION_MAPPING": json.dumps(
            {
                "ldap_to_mo": {
                    "Employee": {
                        "objectClass": "Employee",
                        "_import_to_mo_": "true",
                        "_ldap_attributes_": ["employeeNumber", "givenName", "sn"],
                        "uuid": "{{ employee_uuid or '' }}",
                        "cpr_number": "{{ ldap.employeeNumber }}",
                        "given_name": "{{ ldap.givenName }}",
                        "surname": "{{ ldap.sn }}",
                    },
                },
                "username_generator": {
                    "combinations_to_try": ["FFFX", "LLLX"],
                },
            }
        ),
    }
)
@pytest.mark.usefixtures("test_client", "mo_org_unit")
async def test_dirsync_to_mo(
    graphql_client: GraphQLClient,
    ldap_api: LDAPAPI,
    ldap_org_unit: list[str],
) -> None:
    """Full pipeline: create/edit user in Samba AD, verify it syncs to MO via DirSync.

    This test exercises the complete DirSync-based synchronisation pipeline:

    1. Create a user in Samba AD with a CPR number (``employeeNumber``)
    2. DirSync detects the new user and emits an event
    3. The event handler reads the user from LDAP and creates an employee in MO
    4. Modify a mapped attribute (``givenName``) in LDAP
    5. DirSync detects the change and the employee is updated in MO
    """
    cpr = "2108613133"

    async def get_employee() -> dict[str, Any]:
        employees = await graphql_client._testing__employee_read(
            filter=EmployeeFilter(cpr_numbers=[cpr])
        )
        employee = one(employees.objects)
        validities = one(employee.validities)
        return validities.dict()

    person_dn = combine_dn_strings(["CN=Aage Test"] + ldap_org_unit)

    # LDAP: Create
    given_name = "Aage"
    await ldap_api.ldap_connection.ldap_add(
        dn=person_dn,
        object_class=["top", "person", "organizationalPerson", "user"],
        attributes={
            "objectClass": ["top", "person", "organizationalPerson", "user"],
            "cn": "Aage Test",
            "sn": "Test",
            "givenName": given_name,
            "sAMAccountName": "atest",
            "userPrincipalName": "atest@magenta.dk",
            "employeeNumber": cpr,
        },
    )
    mo_employee = {
        "uuid": ANY,
        "user_key": ANY,
        "cpr_number": cpr,
        "given_name": given_name,
        "surname": "Test",
        "nickname_given_name": "",
        "nickname_surname": "",
    }
    async for attempt in retrying():
        with attempt:
            assert await get_employee() == mo_employee

    # LDAP: Edit mapped attribute (givenName)
    given_name = "Updated"
    await ldap_api.ldap_connection.ldap_modify(
        dn=person_dn,
        changes={
            "givenName": [("MODIFY_REPLACE", given_name)],
        },
    )
    mo_employee = {
        **mo_employee,
        "given_name": given_name,
    }
    async for attempt in retrying():
        with attempt:
            assert await get_employee() == mo_employee
