# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Ariadne-codegen plugins local to this project."""

from importlib.metadata import version
from typing import Any

from ariadne_codegen.plugins.base import Plugin


class ForbidExtraBaseModelPlugin(Plugin):
    """Ariadne plugin that forbids extra fields on the generated BaseModel.

    Ariadne's `BaseModel` does not provide an explicit `Extra` argument, thus Pydantic's
    default behavior behavior of `Extra.allow` is inherited which means that all
    misspellings are simply ignored.

    We wish to instead raise an explicit error whenever a misspelling occur to fail hard
    instead of silently ignoring it, thus we wish to use `Extra.forbid` instead of
    `Extra.allow`, however this requires changing `base_model.py` within the
    autogenerated GraphQL client.

    As of Ariadne codgen 0.7.1 this is not possible by traditional means as the file is
    simply copied verbatim from the Ariadne source code into the generated module, see:

    * https://github.com/mirumee/ariadne-codegen/blob/0.7.1/ariadne_codegen/client_generators/dependencies/base_model.py

    Thus for now we are at an impasse that this plugin attempts to solve.

    The plugin solves the issue by hooking into the `copy_code` hook to insert the
    `extra = Extra.forbid` line and its corresponding imports using string replacement.

    The solution is ugly, but it works and ensures that we no longer end up destroying
    customer data by making a small misspelling in their configuration code.

    See:
    * https://github.com/mirumee/ariadne-codegen/issues/371
    * https://github.com/mirumee/ariadne-codegen/pull/392

    The plugin can be used by inserting it into the `tool.ariadne-codgen` section
    of the `pyproject.toml` file, as shown below:
    ```toml
        [tool.ariadne-codegen]
        target_package_name = "autogenerated_graphql_client"
        ...
        plugins = [
            # Forbid extra fields on the generated BaseModel so typos raise an exception
            "tools.ariadne_plugins.ForbidExtraBaseModelPlugin",  # <-- This
        ]
    ```

    This plugin can be removed once we utilize a newer version of Ariadne codegen
    (one which includes PR392, i.e. >=0.18.0)
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        # This plugin probably does not work on pydantic v2 / newer ariadne versions.
        if version("ariadne-codegen") != "0.7.1":  # pragma: no cover
            raise AssertionError(
                "The ForbidExtraBaseModelPlugin only works on Ariadne 0.7.1"
            )

    def copy_code(self, copied_code: str) -> str:
        # The `copy_code` hook is called for each file being copied out.
        # We wish to ignore all files, execpt the one containing the BaseModel, i.e.
        # base_model.py
        base_model_py_marker = "class BaseModel(PydanticBaseModel):"
        if base_model_py_marker not in copied_code:
            return copied_code

        # At this point we assume that the correct file has been found
        # We now need to import `Extra` from pydantic at the top of the file
        import_marker = "from pydantic import BaseModel as PydanticBaseModel\n"
        assert import_marker in copied_code, f"Could not find {import_marker}"
        # We found the marker, thus we can replace it adding our import
        new_import = "from pydantic import Extra\n"
        copied_code = copied_code.replace(import_marker, import_marker + new_import)

        # We now need to add our BaseModel configuration parameter
        config_marker = "        arbitrary_types_allowed = True\n"
        assert config_marker in copied_code, f"Could not find {config_marker}"
        # We found the marker, thus we can replace it adding our config snippet
        new_config = "        extra = Extra.forbid\n"
        copied_code = copied_code.replace(config_marker, config_marker + new_config)

        # Add our plugin header comment akin to how UnsetInputTypesPlugin does it
        plugin_header = (
            "# This file has been modified by the ForbidExtraBaseModelPlugin\n"
        )
        return plugin_header + copied_code
