# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Dependency injection helpers."""

from collections.abc import AsyncIterable
from contextlib import ExitStack as _ExitStack
from time import perf_counter
from typing import Annotated
from uuid import UUID
from uuid import uuid4

import structlog
from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.events import Event
from fastramqpi.ramqp.depends import Message
from fastramqpi.ramqp.depends import from_context
from ldap3 import Connection as _Connection
from structlog.contextvars import bound_contextvars

from .autogenerated_graphql_client import GraphQLClient as _GraphQLClient
from .config import Settings as _Settings
from .converters import LdapConverter as _LdapConverter
from .dataloaders import DataLoader as _DataLoader
from .import_export import SyncTool as _SyncTool
from .ldap_event_generator import LDAPEventGenerator as _LDAPEventGenerator

GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]
SyncTool = Annotated[_SyncTool, Depends(from_user_context("sync_tool"))]
DataLoader = Annotated[_DataLoader, Depends(from_user_context("dataloader"))]
Settings = Annotated[_Settings, Depends(from_user_context("settings"))]
LdapConverter = Annotated[_LdapConverter, Depends(from_user_context("converter"))]
Connection = Annotated[_Connection, Depends(from_user_context("ldap_connection"))]
LDAPEventGenerator = Annotated[
    _LDAPEventGenerator, Depends(from_user_context("ldap_event_generator"))
]


async def logger_bound_message_id(message: Message) -> AsyncIterable[None]:
    message_id = message.info().get("message_id")
    with bound_contextvars(message_id=message_id):
        yield


async def request_id() -> AsyncIterable[None]:
    request_id = str(uuid4())
    with bound_contextvars(request_id=request_id):
        yield


logger = structlog.stdlib.get_logger()


async def canonical_logline(event: Event[UUID]) -> AsyncIterable[None]:
    """Log the event subject and how long processing it took.

    Handles both directions (MO -> LDAP and LDAP -> MO).
    """
    start = perf_counter()
    try:
        yield
    finally:
        logger.info(
            "Request handled",
            subject=str(event.subject),
            duration=perf_counter() - start,
        )


async def exit_stack() -> AsyncIterable[_ExitStack]:
    with _ExitStack() as exit_stack:
        yield exit_stack


ExitStack = Annotated[_ExitStack, Depends(exit_stack)]
