# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""LDAP change event generation using Microsoft DirSync control.

DirSync (LDAP_SERVER_DIRSYNC_OID 1.2.840.113556.1.4.841) is an Active
Directory specific control for incremental synchronization.  Unlike the
modifyTimestamp-based approach in ``LDAPEventGenerator``, DirSync uses an
opaque server-side cookie that tracks the replication state of the polled
domain controller, so changes are never missed because of replication delays
or timestamp precision, and only objects whose requested attributes changed
are reported.

The integration is deliberately limited to a single domain controller (see
``Settings.check_at_most_one_controller``), so failover between controllers
is out of scope.  A cookie from one controller can be presented to another,
but the reply may then be a full resynchronization.

Constraints imposed by the DirSync protocol:
* The search base MUST be a naming context (root DN), not an arbitrary subtree.
  Events are therefore filtered client-side to ``ldap_ous_to_search_in``.
* The caller MUST have read access to in-scope objects and attributes.  For
  deletion detection, the caller MUST also have read access to the
  ``CN=Deleted Objects`` container.
"""

import asyncio
from collections.abc import Iterable
from contextlib import AbstractAsyncContextManager
from contextlib import suppress
from typing import Any
from typing import Protocol
from typing import Self

import ldap3
import structlog
from fastramqpi.context import Context
from ldap3 import BASE
from ldap3 import NO_ATTRIBUTES
from ldap3 import SAFE_SYNC
from ldap3.utils.dn import safe_dn
from more_itertools import one
from sqlalchemy import LargeBinary
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.ext.asyncio import async_sessionmaker
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

from .autogenerated_graphql_client.client import GraphQLClient
from .config import Settings
from .database import Base
from .ldap import construct_server
from .ldap import get_base_connection_kwargs
from .ldap_emit import publish_uuids
from .types import DN
from .types import LDAPUUID
from .utils import combine_dn_strings

logger = structlog.stdlib.get_logger()

# Tombstone attributes requested in addition to the mapped attributes so that
# deletions are reported (per Microsoft's DirSync guidance) and can be scoped
# to the OU the object lived in before it was moved to CN=Deleted Objects.
TOMBSTONE_ATTRIBUTES = {"isDeleted", "lastKnownParent"}


class DirSyncPages(Protocol):
    """The subset of ``ldap3.extend.microsoft.dirSync.DirSync`` we rely on."""

    more_results: bool
    cookie: bytes

    def loop(self) -> list[dict[str, Any]]: ...


def collect_dirsync_entries(ds: DirSyncPages) -> tuple[list[dict[str, Any]], bytes]:
    """Drain every DirSync page and return the entries and the final cookie.

    A single ``loop()`` call fetches one page. The server sets ``more_results``
    while further pages remain, so keep going until it clears and only then
    hand back the cookie, which then represents the complete change set.
    """
    entries: list[dict[str, Any]] = []
    while ds.more_results:
        response = ds.loop()
        entries.extend(e for e in response if e["type"] == "searchResEntry")
    return entries, ds.cookie


def strip_extended_dn(dn: DN) -> DN:
    """Remove the ``<GUID=...>;<SID=...>;`` prefixes of an extended DN.

    DirSync responses carry the LDAP_SERVER_EXTENDED_DN_OID control, which
    prefixes DNs with one or more angle-bracketed components.
    """
    while dn.startswith("<"):
        _, _, dn = dn.partition(";")
    return dn


def dn_in_search_bases(dn: DN, search_bases: Iterable[DN]) -> bool:
    """Whether ``dn`` is at or below any of ``search_bases``.

    Comparison is done on normalised DNs and is case-insensitive, as Active
    Directory does not preserve the case of configured RDNs.
    """
    normalised = safe_dn(strip_extended_dn(dn)).lower()
    for base in search_bases:
        normalised_base = safe_dn(base).lower()
        if normalised == normalised_base or normalised.endswith("," + normalised_base):
            return True
    return False


def dirsync_entries_to_uuids(
    entries: Iterable[dict[str, Any]],
    unique_id_field: str,
    search_bases: Iterable[DN],
) -> set[LDAPUUID]:
    """Map DirSync entries to the UUIDs of objects within the configured OUs.

    Deleted objects are reported from ``CN=Deleted Objects``, so they are
    scoped by ``lastKnownParent`` rather than by their current DN.
    """
    search_bases = list(search_bases)
    uuids: set[LDAPUUID] = set()
    for entry in entries:
        attributes = entry["attributes"]
        dn = entry["dn"]

        is_deleted = attributes.get("isDeleted") in (True, "TRUE")
        scope_dn = attributes.get("lastKnownParent") if is_deleted else dn
        if scope_dn is None:  # pragma: no cover
            logger.warning("Got deleted DirSync entry without lastKnownParent", dn=dn)
            continue
        if not dn_in_search_bases(scope_dn, search_bases):
            logger.debug("Ignoring DirSync entry outside configured OUs", dn=dn)
            continue

        uuid = attributes.get(unique_id_field)
        if uuid is None:  # pragma: no cover
            logger.warning("Got DirSync entry without uuid", dn=dn)
            continue
        uuids.add(LDAPUUID(uuid))
    return uuids


class DirSyncState(Base):
    """Singleton row storing the DirSync cookie.

    DirSync always operates on the entire naming context, so there is exactly
    one cookie per domain — no need to key by search base.
    """

    __tablename__ = "dirsync_state"

    id: Mapped[int] = mapped_column(primary_key=True)
    cookie: Mapped[bytes | None] = mapped_column(
        LargeBinary, default=None, nullable=True
    )


def configure_dirsync_connection(settings: Settings) -> ldap3.Connection:
    """Configure an LDAP connection suitable for DirSync operations.

    DirSync requires a synchronous connection that does not transparently
    reconnect, as ldap3 stashes per-poll DirSync state on the connection
    object which a mid-poll reconnect would discard. ``SAFE_RESTARTABLE``
    is therefore incompatible, and plain ``SYNC`` is not thread-safe.

    ``SAFE_SYNC`` threads the needle: it is thread-safe (acquiring an
    internal lock per operation) but does not reconnect. The DirSync
    extension explicitly supports it, reading results from the return tuple
    rather than connection state when ``strategy.thread_safe`` is set.
    """
    server_config = one(settings.ldap_controllers)
    server = construct_server(server_config)

    connection_kwargs: dict[str, Any] = {
        "server": server,
        "client_strategy": SAFE_SYNC,
        "read_only": True,
        **get_base_connection_kwargs(settings),
    }

    return ldap3.Connection(**connection_kwargs)


class DirSyncEventGenerator(AbstractAsyncContextManager):
    def __init__(
        self,
        sessionmaker: async_sessionmaker[AsyncSession],
        settings: Settings,
        graphql_client: GraphQLClient,
    ) -> None:
        """Periodically poll LDAP for changes using Microsoft DirSync control."""
        self.sessionmaker = sessionmaker
        self.settings = settings
        self.graphql_client = graphql_client
        self.dirsync_connection = configure_dirsync_connection(settings)

        self._poller_task: asyncio.Task | None = None

    async def __aenter__(self) -> Self:
        """Start event generator."""
        await asyncio.to_thread(self._check_deleted_objects_readable)
        self._poller_task = self.setup_poller()
        return self

    async def __aexit__(
        self, __exc_type: object, __exc_value: object, __traceback: object
    ) -> None:
        """Stop event generator."""
        if self._poller_task is not None:
            self._poller_task.cancel()
            with suppress(asyncio.CancelledError):
                await self._poller_task
        self.dirsync_connection.unbind()

    async def healthcheck(self, context: dict | Context) -> bool:
        return self._poller_task is not None and not self._poller_task.done()

    def _check_deleted_objects_readable(self) -> None:
        """Probe whether the bind account can read the Deleted Objects container.

        Under DirSync OBJECT_SECURITY mode, deletion events are only reported
        for objects the account could read before deletion, and only if the
        account can read the tombstone in ``CN=Deleted Objects``.  This probe
        surfaces a missing grant at startup rather than silently dropping
        deletion events.

        Whether a missing grant is fatal is controlled by
        ``settings.ldap_dirsync_require_deleted_objects_access``. When it is
        False the problem is only logged as a warning, with the exact
        ``dsacls`` command needed to grant access.

        Raises:
            RuntimeError: If the container is not readable and access is
                required by settings.
        """
        deleted_objects_dn = f"CN=Deleted Objects,{self.settings.ldap_search_base}"
        conn = self.dirsync_connection
        message = (
            f"Unable to read {deleted_objects_dn}. "
            f"Deletion detection requires read access to the Deleted Objects "
            f"container. Grant it with: "
            f'dsacls "{deleted_objects_dn}" /G "<domain>\\<service-account>:RP;LC"'
        )

        def _probe() -> bool:
            # SAFE_SYNC is a thread-safe strategy, so ldap3 returns a
            # (status, result, response, request) tuple instead of a bool.
            status, _, _, _ = conn.search(
                search_base=deleted_objects_dn,
                search_filter="(objectClass=*)",
                search_scope=BASE,
                attributes=NO_ATTRIBUTES,
            )
            return status

        error: Exception | None = None
        try:
            readable = _probe()
        except Exception as exc:
            readable = False
            error = exc

        if readable:
            return

        if self.settings.ldap_dirsync_require_deleted_objects_access:
            raise RuntimeError(message) from error

        logger.warning(
            "Deleted Objects container is not readable, deletion events will "
            "not be detected",
            dn=deleted_objects_dn,
            hint=message,
            error=repr(error) if error else None,
        )

    def setup_poller(self) -> asyncio.Task:
        def done_callback(future):
            # Silence CancelledErrors on shutdown
            with suppress(asyncio.CancelledError):
                # This ensures exceptions go to the terminal
                future.result()

        handle = asyncio.create_task(self._poller())
        handle.add_done_callback(done_callback)
        return handle

    async def poll(
        self,
        cookie: bytes | None,
    ) -> tuple[set[LDAPUUID], bytes]:
        """Poll the LDAP server for changes using DirSync control.

        Args:
            cookie:
                DirSync cookie from a previous poll, or ``None`` for initial sync.

        Returns:
            Tuple of (set of changed UUIDs, new cookie).
        """
        search_base = self.settings.ldap_search_base
        logger.debug(
            "Searching for DirSync changes",
            search_base=search_base,
            has_cookie=cookie is not None,
        )

        # To improve performance and reduce noise, we only listen for changes to
        # objects with object classes that we are configured to consume.
        relevant_object_classes = {
            self.settings.ldap_object_class,
            *self.settings.conversion_mapping.ldap_to_mo_any,
        }
        object_class_filter = "".join(
            f"(objectClass={cls})" for cls in relevant_object_classes
        )
        sync_filter = f"(|{object_class_filter})"

        conn = self.dirsync_connection

        # DirSync only reports objects where a *requested* attribute changed
        # (per MS-ADTS).  Mirror the attribute set from ldap_amqp.py so we
        # detect exactly the changes we care about, plus the tombstone
        # attributes needed to report and scope deletions.
        attributes = list(
            (self.settings.relevant_ldap_attributes | TOMBSTONE_ATTRIBUTES) - {"dn"}
        )

        def _run_dirsync() -> tuple[list[dict[str, Any]], bytes]:
            ds = conn.extend.microsoft.dir_sync(
                sync_base=search_base,
                sync_filter=sync_filter,
                attributes=attributes,
                cookie=cookie,
                object_security=True,
            )
            return collect_dirsync_entries(ds)

        entries, new_cookie = await asyncio.to_thread(_run_dirsync)

        # DirSync cannot be scoped below the naming context, so restrict the
        # events client-side to the OUs the rest of the integration operates on.
        search_bases = {
            combine_dn_strings([ou, search_base])
            for ou in self.settings.ldap_ous_to_search_in
        }
        uuids = dirsync_entries_to_uuids(
            entries, self.settings.ldap_unique_id_field, search_bases
        )
        return uuids, new_cookie

    async def _poller(self) -> None:
        """Poll the LDAP server continuously every ``settings.poll_time`` seconds."""
        logger.info("DirSync poller started")
        while True:
            await asyncio.shield(self._generate_events())
            # Wait for a while before running again
            await asyncio.sleep(self.settings.poll_time)

    async def _generate_events(self) -> None:
        # Ensure that a singleton state row exists
        # We do creates separately to support update locks in normal operation
        async with self.sessionmaker() as session, session.begin():
            state = await session.scalar(select(DirSyncState).with_for_update())
            state = state or DirSyncState()
            session.add(state)

        async with self.sessionmaker() as session, session.begin():
            # Get DirSync state from database for updating
            state = await session.scalar(select(DirSyncState).with_for_update())
            assert state is not None

            # Fetch changes and emit events for them
            uuids, new_cookie = await self.poll(state.cookie)

            # Only publish events when there are actual changes
            # DirSync returns an empty set when no changes have occurred
            if uuids:
                await publish_uuids(self.settings, self.graphql_client, list(uuids))

            # Always update the cookie to advance the DirSync position
            state.cookie = new_cookie
            session.add(state)
