# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Annotated

import structlog
from fastapi import APIRouter
from fastapi import Depends
from fastramqpi.events import Event
from fastramqpi.ramqp.depends import get_payload_as_type
from more_itertools import only

from . import depends
from .autogenerated_graphql_client import ListenerFilter
from .autogenerated_graphql_client import NamespaceFilter
from .depends import DataLoader
from .depends import Settings
from .depends import SyncTool
from .exceptions import AcknowledgeException
from .types import LDAPUUID
from .types import CPRNumber

logger = structlog.stdlib.get_logger()


ldap2mo_router = APIRouter(prefix="/ldap2mo")

PayloadUUID = Annotated[LDAPUUID, Depends(get_payload_as_type(LDAPUUID))]


@ldap2mo_router.post("/uuid")
async def http_process_uuid(
    settings: Settings,
    sync_tool: SyncTool,
    dataloader: DataLoader,
    event: Event[LDAPUUID],
) -> None:
    uuid = event.subject
    logger.info("Received LDAP event", uuid=uuid)

    if uuid in settings.ldap_uuids_to_ignore:
        logger.warning("LDAP event ignored due to ignore-list", ldap_uuid=uuid)
        return

    attributes = {"objectClass", settings.ldap_unique_id_field}
    if settings.ldap_cpr_attribute:
        attributes.add(settings.ldap_cpr_attribute)

    ldap_object = await dataloader.ldapapi.get_object_by_uuid(
        uuid, attributes=attributes
    )
    if ldap_object is None:
        logger.error("LDAP UUID could not be found", uuid=uuid)
        raise AcknowledgeException("LDAP UUID could not be found")

    dn = ldap_object.dn
    # Ignore changes to non-employee objects
    assert hasattr(ldap_object, "objectClass")
    ldap_object_classes = ldap_object.objectClass

    # TODO: Eliminate this branch by handling employees as any other object
    employee_object_class = settings.ldap_object_class
    if employee_object_class in ldap_object_classes:
        logger.info("Handling employee", ldap_object_classes=ldap_object_classes)
        await sync_tool.import_single_user(ldap_object)

    for object_class in settings.conversion_mapping.ldap_to_mo_any:
        if object_class in ldap_object_classes:
            logger.info(
                "Handling LDAP event",
                object_class=object_class,
                ldap_object_classes=ldap_object_classes,
            )
            await sync_tool.import_single_object_class(object_class, dn)


@ldap2mo_router.post("/reconcile")
async def http_reconcile_uuid(
    settings: Settings,
    dataloader: DataLoader,
    graphql_client: depends.GraphQLClient,
    event: Event[LDAPUUID],
) -> None:
    uuid = event.subject
    logger.info("Received LDAP event (Reconcile)", uuid=uuid)

    if uuid in settings.ldap_uuids_to_ignore:
        logger.warning("LDAP event ignored due to ignore-list", ldap_uuid=uuid)
        return

    attributes = set()
    if settings.ldap_cpr_attribute:
        attributes.add(settings.ldap_cpr_attribute)

    ldap_object = await dataloader.ldapapi.get_object_by_uuid(
        uuid, attributes=attributes
    )

    if ldap_object is None:
        logger.error("LDAP UUID could not be found", uuid=uuid)
        raise AcknowledgeException("LDAP UUID could not be found")

    cpr: CPRNumber | None = None
    if settings.ldap_cpr_attribute:
        raw_cpr = getattr(ldap_object, settings.ldap_cpr_attribute, None)
        if isinstance(raw_cpr, list):
            raw_cpr = only(raw_cpr)
        if raw_cpr:
            cpr = CPRNumber(str(raw_cpr))

    person_uuid = await dataloader.find_mo_employee_uuid(cpr, uuid)
    if person_uuid is None:
        return
    # We handle reconciliation by seeding events into the normal processing queue
    me = await graphql_client.who_am_i()
    listeners = await graphql_client.read_event_listeners(
        filter=ListenerFilter(
            namespaces=NamespaceFilter(names=["mo"]),
            owners=[me.actor.uuid],
            user_keys=[f"{settings.event_namespace}_internal_process_person"],
        ),
    )
    listener = only(listeners.objects)
    if listener is None:
        # Not listening to changes in MO
        return
    await graphql_client.person_refresh(uuids=[person_uuid], listener=listener.uuid)
